import assert from "node:assert/strict";
import { Buffer } from "node:buffer";
import { spawnSync } from "node:child_process";
import { copyFileSync, mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import test from "node:test";
import { UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END, mapUnsigned32SampleBatchToBoundedTicket } from "@draft-table/engine";
import { fictionalCollationCapabilities } from "./fictional-collation-capabilities.mjs";

const moduleKey = "DRAFT_TABLE_TEST_FINITE_BATCH_PLAN_POSITION_TRANSITION_MODULE";

const needMoreContract = "finite batch plan position need-more cannot select remove or register", needMoreMarker = "FINITE_BATCH_PLAN_POSITION_NEED_MORE_CONTRACT_EXECUTED";
test(needMoreContract, async () => {
  console.log(needMoreMarker);
  const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl);
  const [transition, finite, pack, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]);
  const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected");
  const state = pack.readOmensPackCollationPlanPoolDrawStateForTransition(initialized.plan), position = pack.readOmensPackCollationPlanLayoutForTransition(initialized.plan).slots[0], pool = state.poolStates.find((entry) => entry.poolReference === position.resolvedPool), retry = UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END - UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END % pool.poolTotalWeight;
  let selected = 0, removed = 0, registered = 0, result;
  assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatchForTest(initialized.plan, [retry], mapUnsigned32SampleBatchToBoundedTicket, () => { selected++; throw new Error("NEED_MORE_MUST_NOT_SELECT_REMOVE_OR_REGISTER"); }, () => { removed++; throw new Error("NEED_MORE_MUST_NOT_SELECT_REMOVE_OR_REGISTER"); }, () => { registered++; throw new Error("NEED_MORE_MUST_NOT_SELECT_REMOVE_OR_REGISTER"); }); }, "NEED_MORE_MUST_NOT_SELECT_REMOVE_OR_REGISTER");
  assert.deepEqual(result, { state: "needs-sample", consumedSamples: 1 }, "NEED_MORE_MUST_NOT_SELECT_REMOVE_OR_REGISTER"); assert.equal(selected + removed + registered, 0, "NEED_MORE_MUST_NOT_SELECT_REMOVE_OR_REGISTER"); assert.equal(pack.readOmensPackCollationPlanNextPositionForTransition(initialized.plan), 0, "NEED_MORE_MUST_NOT_SELECT_REMOVE_OR_REGISTER");
});
test("need-more no-side-effect semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = 'if (mapping.state === "needs-sample") return needsSample(mapping.consumedSamples);', original = readFileSync(sourcePath, "utf8");
  const mutated = original.replace(anchor, 'if (mapping.state === "needs-sample") { const injectedIdentity = selectIdentity(current.poolDrawState, poolReference, 0) as OfficialIdentityReference; const injectedState = removeIdentity(current.poolDrawState, poolReference, injectedIdentity) as OmensPackLocalPoolDrawState; registerPlan(plan, positionReference, injectedIdentity, injectedState); return needsSample(mapping.consumedSamples); }');
  assert.equal(original.split(anchor).length - 1, 1, "NEED_MORE_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "NEED_MORE_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-need-more-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${needMoreContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${needMoreMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(needMoreContract)).length, 1); assert.equal(lines.filter((line) => line.includes("NEED_MORE_MUST_NOT_SELECT_REMOVE_OR_REGISTER")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const ticketContract = "finite batch plan position passes accepted ticket unchanged", ticketMarker = "FINITE_BATCH_PLAN_POSITION_TICKET_CONTRACT_EXECUTED";
test(ticketContract, async () => {
  console.log(ticketMarker);
  const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl);
  const [transition, finite, pack, stateModule, selector, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("pack-local-pool-draw-state.ts", directory)), import(new URL("pack-local-pool-ticket-selection.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]);
  const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); const drawState = pack.readOmensPackCollationPlanPoolDrawStateForTransition(initialized.plan), poolReference = pack.readOmensPackCollationPlanLayoutForTransition(initialized.plan).slots[0].resolvedPool, pool = drawState.poolStates.find((entry) => entry.poolReference === poolReference), ticket = pool.officialIdentityChoices[0].cumulativeExclusiveEnd - 1; let result;
  assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatchForTest(initialized.plan, [ticket], mapUnsigned32SampleBatchToBoundedTicket, selector.selectOmensPackLocalPoolOfficialIdentityByTicket, stateModule.removeOmensPackLocalPoolOfficialIdentity, pack.registerOmensPackCollationPlanPositionTransition); }, "ACCEPTED_TICKET_MUST_PASS_UNCHANGED"); assert.equal(result.officialIdentityReference, pool.officialIdentityChoices[0].officialIdentityReference, "ACCEPTED_TICKET_MUST_PASS_UNCHANGED");
});
test("accepted-ticket semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "selectIdentity(current.poolDrawState, poolReference, mapping.ticket)", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, "selectIdentity(current.poolDrawState, poolReference, mapping.ticket + 1)"); assert.equal(original.split(anchor).length - 1, 1, "TICKET_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "TICKET_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-ticket-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${ticketContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${ticketMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(ticketContract)).length, 1); assert.equal(lines.filter((line) => line.includes("ACCEPTED_TICKET_MUST_PASS_UNCHANGED")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const consumedContract = "finite batch plan position preserves engine consumed count", consumedMarker = "FINITE_BATCH_PLAN_POSITION_CONSUMED_CONTRACT_EXECUTED";
test(consumedContract, async () => {
  console.log(consumedMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, pack, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); const state = pack.readOmensPackCollationPlanPoolDrawStateForTransition(initialized.plan), pool = state.poolStates.find((entry) => entry.poolReference === initialized.layoutReference.slots[0].resolvedPool), retry = UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END - UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END % pool.poolTotalWeight, result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [retry, 0]); assert.equal(result.consumedSamples, 2, "ENGINE_CONSUMED_COUNT_MUST_PASS_UNCHANGED");
});
test("consumed-count semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "mapping.consumedSamples, positionReference, officialIdentityReference, nextPlan", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, "0, positionReference, officialIdentityReference, nextPlan"); assert.equal(original.split(anchor).length - 1, 1, "CONSUMED_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "CONSUMED_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-consumed-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${consumedContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${consumedMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(consumedContract)).length, 1); assert.equal(lines.filter((line) => line.includes("ENGINE_CONSUMED_COUNT_MUST_PASS_UNCHANGED")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const positionContract = "finite batch plan transition uses exact current position and resolved pool", positionMarker = "FINITE_BATCH_PLAN_POSITION_SCOPE_CONTRACT_EXECUTED";
test(positionContract, async () => {
  console.log(positionMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, pack, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); let plan = initialized.plan; for (let index = 0; index < 3; index++) plan = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(plan, [0]).nextPlan; let result; assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(plan, [0]); }, "CURRENT_POSITION_AND_RESOLVED_POOL_MUST_BE_EXACT"); assert.equal(result.positionReference, initialized.layoutReference.slots[3], "CURRENT_POSITION_AND_RESOLVED_POOL_MUST_BE_EXACT");
});
test("current-position resolved-pool semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "const poolReference = positionReference.resolvedPool;", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, "const poolReference = current.poolDrawState.poolStates[0].poolReference;"); assert.equal(original.split(anchor).length - 1, 1, "POSITION_SCOPE_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "POSITION_SCOPE_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-scope-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${positionContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${positionMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(positionContract)).length, 1); assert.equal(lines.filter((line) => line.includes("CURRENT_POSITION_AND_RESOLVED_POOL_MUST_BE_EXACT")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const removalContract = "finite batch plan transition removes exact selected identity from same pool only", removalMarker = "FINITE_BATCH_PLAN_POSITION_REMOVAL_CONTRACT_EXECUTED";
test(removalContract, async () => {
  console.log(removalMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, pack, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); const prior = pack.readOmensPackCollationPlanPoolDrawStateForTransition(initialized.plan), selectedPool = prior.poolStates[0], untouched = prior.poolStates[8]; let result; assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]); }, "EXACT_IDENTITY_SAME_POOL_ONLY_REMOVAL_REQUIRED"); const next = pack.readOmensPackCollationPlanPoolDrawStateForTransition(result.nextPlan); assert.equal(next.poolStates[0].officialIdentityChoices.some((choice) => choice.officialIdentityReference === result.officialIdentityReference), false, "EXACT_IDENTITY_SAME_POOL_ONLY_REMOVAL_REQUIRED"); assert.notEqual(next.poolStates[0], selectedPool, "EXACT_IDENTITY_SAME_POOL_ONLY_REMOVAL_REQUIRED"); assert.equal(next.poolStates[8], untouched, "EXACT_IDENTITY_SAME_POOL_ONLY_REMOVAL_REQUIRED");
});
test("selected-identity same-pool removal semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "current.poolDrawState, poolReference, officialIdentityReference\n  ) as OmensPackLocalPoolDrawState;", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, "current.poolDrawState, current.poolDrawState.poolStates[8].poolReference, current.poolDrawState.poolStates[8].officialIdentityChoices[0].officialIdentityReference\n  ) as OmensPackLocalPoolDrawState;"); assert.equal(original.split(anchor).length - 1, 1, "REMOVAL_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "REMOVAL_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-removal-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${removalContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${removalMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(removalContract)).length, 1); assert.equal(lines.filter((line) => line.includes("EXACT_IDENTITY_SAME_POOL_ONLY_REMOVAL_REQUIRED")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const cursorContract = "finite batch plan transition advances cursor exactly one", cursorMarker = "FINITE_BATCH_PLAN_POSITION_CURSOR_CONTRACT_EXECUTED";
test(cursorContract, async () => {
  console.log(cursorMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, pack, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); let result; assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]); }, "CURSOR_MUST_ADVANCE_EXACTLY_ONE"); assert.equal(pack.readOmensPackCollationPlanNextPositionForTransition(result.nextPlan), 1, "CURSOR_MUST_ADVANCE_EXACTLY_ONE");
});
test("cursor increment semantic mutation fails its exact named contract", () => {
  const transitionPath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), planPath = new URL("../src/pack-collation-plan.ts", import.meta.url), anchor = "nextPosition: prior.nextPosition + 1", original = readFileSync(planPath, "utf8"), mutated = original.replace(anchor, "nextPosition: prior.nextPosition + 2"); assert.equal(original.split(anchor).length - 1, 1, "CURSOR_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "CURSOR_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-cursor-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "pack-collation-plan.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, fileURLToPath(transitionPath).split("/").at(-1))).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${cursorContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${cursorMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(cursorContract)).length, 1); assert.equal(lines.filter((line) => line.includes("CURSOR_MUST_ADVANCE_EXACTLY_ONE")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const historyContract = "finite batch plan transition does not mutate or reuse old plan", historyMarker = "FINITE_BATCH_PLAN_POSITION_HISTORY_CONTRACT_EXECUTED";
test(historyContract, async () => {
  console.log(historyMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, pack, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); const oldState = pack.readOmensPackCollationPlanPoolDrawStateForTransition(initialized.plan), result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]); assert.notEqual(result.nextPlan, initialized.plan, "OLD_PLAN_MUST_NOT_BE_MUTATED_OR_REUSED"); assert.equal(pack.readOmensPackCollationPlanNextPositionForTransition(initialized.plan), 0, "OLD_PLAN_MUST_NOT_BE_MUTATED_OR_REUSED"); assert.equal(pack.readOmensPackCollationPlanPoolDrawStateForTransition(initialized.plan), oldState, "OLD_PLAN_MUST_NOT_BE_MUTATED_OR_REUSED");
});
test("old-plan reuse semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "mapping.consumedSamples, positionReference, officialIdentityReference, nextPlan\n  );", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, "mapping.consumedSamples, positionReference, officialIdentityReference, plan\n  );"); assert.equal(original.split(anchor).length - 1, 1, "HISTORY_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "HISTORY_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-history-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${historyContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${historyMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(historyContract)).length, 1); assert.equal(lines.filter((line) => line.includes("OLD_PLAN_MUST_NOT_BE_MUTATED_OR_REUSED")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const retentionContract = "finite batch plan transition retains exact layout and compiled capability", retentionMarker = "FINITE_BATCH_PLAN_POSITION_RETENTION_CONTRACT_EXECUTED";
test(retentionContract, async () => {
  console.log(retentionMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, pack, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); let result; assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]); }, "NEXT_PLAN_MUST_RETAIN_EXACT_LAYOUT_AND_CAPABILITY"); assert.equal(pack.readOmensPackCollationPlanLayoutForTransition(result.nextPlan), initialized.layoutReference, "NEXT_PLAN_MUST_RETAIN_EXACT_LAYOUT_AND_CAPABILITY"); assert.equal(pack.readOmensPackCollationPlanTablesForTest(result.nextPlan), tables, "NEXT_PLAN_MUST_RETAIN_EXACT_LAYOUT_AND_CAPABILITY");
});
test("next-plan layout-capability retention semantic mutation fails its exact named contract", () => {
  const transitionPath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), planPath = new URL("../src/pack-collation-plan.ts", import.meta.url), anchor = "layoutReference: prior.layoutReference,", original = readFileSync(planPath, "utf8"), mutated = original.replace(anchor, "layoutReference: prior.tables.layoutChoices[1].layoutReference,"); assert.equal(original.split(anchor).length - 1, 1, "RETENTION_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "RETENTION_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-retention-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "pack-collation-plan.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, fileURLToPath(transitionPath).split("/").at(-1))).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${retentionContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${retentionMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(retentionContract)).length, 1); assert.equal(lines.filter((line) => line.includes("NEXT_PLAN_MUST_RETAIN_EXACT_LAYOUT_AND_CAPABILITY")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const terminalContract = "finite batch plan position terminal cursor rejects before mapping", terminalMarker = "FINITE_BATCH_PLAN_POSITION_TERMINAL_CONTRACT_EXECUTED";
test(terminalContract, async () => {
  console.log(terminalMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); let plan = initialized.plan; for (let index = 0; index < 14; index++) plan = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(plan, [0]).nextPlan; assert.throws(() => transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(plan, []), { code: "OMENS_PACK_COLLATION_PLAN_POSITION_TRANSITION_FAILED" }, "TERMINAL_CURSOR_MUST_REJECT_BEFORE_MAPPING");
});
test("terminal-cursor semantic mutation fails its exact named contract", () => {
  const transitionPath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), planPath = new URL("../src/pack-collation-plan.ts", import.meta.url), anchor = "  if (!isSafeInteger(parts.nextPosition) || parts.nextPosition < 0 ||\n    parts.nextPosition >= EXPECTED_POSITION_COUNT) return fail();\n  const positionReference = parts.layoutReference.slots[parts.nextPosition];\n  if (positionReference === undefined || !isFrozen(positionReference) ||\n    positionReference.position !== parts.nextPosition + 1) return fail();", replacement = "  if (!isSafeInteger(parts.nextPosition) || parts.nextPosition < 0 ||\n    parts.nextPosition > EXPECTED_POSITION_COUNT) return fail();\n  const positionReference = parts.layoutReference.slots[parts.nextPosition] ?? parts.layoutReference.slots[0];\n  if (!isFrozen(positionReference)) return fail();", original = readFileSync(planPath, "utf8"), mutated = original.replace(anchor, replacement); assert.equal(original.split(anchor).length - 1, 1, "TERMINAL_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "TERMINAL_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-terminal-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "pack-collation-plan.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, fileURLToPath(transitionPath).split("/").at(-1))).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${terminalContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${terminalMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(terminalContract)).length, 1); assert.equal(lines.filter((line) => line.includes("TERMINAL_CURSOR_MUST_REJECT_BEFORE_MAPPING")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});
