import assert from "node:assert/strict";
import { Buffer } from "node:buffer";
import { spawnSync } from "node:child_process";
import { copyFileSync, mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import test from "node:test";
import { fictionalCollationCapabilities } from "./fictional-collation-capabilities.mjs";

// Task-module capture inventory: Array.isArray and Object.defineProperty are proved in the
// owning mutation suite, and Object.freeze by its existing hardened-output cross-attack
// (captain-measured live swap). This file independently proves Object.getOwnPropertyDescriptor,
// Reflect.ownKeys, Object.isFrozen, Number.isSafeInteger, and the one shared captured
// WeakSet has/add pair used by both independent freshness sets. WeakSet construction and
// Function.call/bind are completed during module evaluation, before any exported call or
// hostile caller read can run, so no post-import live-global substitution can reach them.
const moduleKey = "DRAFT_TABLE_TEST_FINITE_BATCH_PLAN_POSITION_TRANSITION_MODULE";
const safeDefineProperty = Object.defineProperty;
const safeGetOwnPropertyDescriptor = Object.getOwnPropertyDescriptor;
const safeWeakSetHas = Function.prototype.call.bind(WeakSet.prototype.has);
const safeWeakSetAdd = Function.prototype.call.bind(WeakSet.prototype.add);

const descriptorContract = "finite batch plan position captures Object.getOwnPropertyDescriptor before hostile caller reads", descriptorMarker = "FINITE_BATCH_PLAN_POSITION_GET_OWN_PROPERTY_DESCRIPTOR_CAPTURE_CONTRACT_EXECUTED";
test(descriptorContract, async () => {
  console.log(descriptorMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); const descriptor = safeGetOwnPropertyDescriptor(Object, "getOwnPropertyDescriptor"), samples = [0]; let result;
  safeDefineProperty(samples, "0", { configurable: true, enumerable: true, get() { safeDefineProperty(Object, "getOwnPropertyDescriptor", { ...descriptor, value: () => { throw new Error("poisoned"); } }); return 0; } });
  try { assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, samples); }, "GET_OWN_PROPERTY_DESCRIPTOR_CAPTURE_MUST_SURVIVE_HOSTILE_CALLER_READ"); } finally { safeDefineProperty(Object, "getOwnPropertyDescriptor", descriptor); }
  assert.equal(result.state, "selected", "GET_OWN_PROPERTY_DESCRIPTOR_CAPTURE_MUST_SURVIVE_HOSTILE_CALLER_READ");
});
test("Object.getOwnPropertyDescriptor capture semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "const getOwnPropertyDescriptor: typeof Object.getOwnPropertyDescriptor = Object.getOwnPropertyDescriptor;", replacement = "const getOwnPropertyDescriptor = ((value: object, property: PropertyKey) => Object.getOwnPropertyDescriptor(value, property)) as typeof Object.getOwnPropertyDescriptor;", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, replacement); assert.equal(original.split(anchor).length - 1, 1, "GET_OWN_PROPERTY_DESCRIPTOR_CAPTURE_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "GET_OWN_PROPERTY_DESCRIPTOR_CAPTURE_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-get-own-property-descriptor-capture-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${descriptorContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${descriptorMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(descriptorContract)).length, 1); assert.equal(lines.filter((line) => line.includes("GET_OWN_PROPERTY_DESCRIPTOR_CAPTURE_MUST_SURVIVE_HOSTILE_CALLER_READ")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const ownKeysContract = "finite batch plan position captures Reflect.ownKeys before hostile caller reads", ownKeysMarker = "FINITE_BATCH_PLAN_POSITION_OWN_KEYS_CAPTURE_CONTRACT_EXECUTED";
test(ownKeysContract, async () => {
  console.log(ownKeysMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); const descriptor = safeGetOwnPropertyDescriptor(Reflect, "ownKeys"), samples = [0]; let result;
  safeDefineProperty(samples, "0", { configurable: true, enumerable: true, get() { safeDefineProperty(Reflect, "ownKeys", { ...descriptor, value: () => { throw new Error("poisoned"); } }); return 0; } });
  try { assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, samples); }, "OWN_KEYS_CAPTURE_MUST_SURVIVE_HOSTILE_CALLER_READ"); } finally { safeDefineProperty(Reflect, "ownKeys", descriptor); }
  assert.equal(result.state, "selected", "OWN_KEYS_CAPTURE_MUST_SURVIVE_HOSTILE_CALLER_READ");
});
test("Reflect.ownKeys capture semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "const ownKeys: typeof Reflect.ownKeys = Reflect.ownKeys;", replacement = "const ownKeys = ((value: object) => Reflect.ownKeys(value)) as typeof Reflect.ownKeys;", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, replacement); assert.equal(original.split(anchor).length - 1, 1, "OWN_KEYS_CAPTURE_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "OWN_KEYS_CAPTURE_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-own-keys-capture-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${ownKeysContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${ownKeysMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(ownKeysContract)).length, 1); assert.equal(lines.filter((line) => line.includes("OWN_KEYS_CAPTURE_MUST_SURVIVE_HOSTILE_CALLER_READ")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const isFrozenContract = "finite batch plan position captures Object.isFrozen before hostile caller reads", isFrozenMarker = "FINITE_BATCH_PLAN_POSITION_IS_FROZEN_CAPTURE_CONTRACT_EXECUTED";
test(isFrozenContract, async () => {
  console.log(isFrozenMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); const descriptor = safeGetOwnPropertyDescriptor(Object, "isFrozen"), samples = [0]; let result;
  safeDefineProperty(samples, "0", { configurable: true, enumerable: true, get() { safeDefineProperty(Object, "isFrozen", { ...descriptor, value: () => { throw new Error("poisoned"); } }); return 0; } });
  try { assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, samples); }, "IS_FROZEN_CAPTURE_MUST_SURVIVE_HOSTILE_CALLER_READ"); } finally { safeDefineProperty(Object, "isFrozen", descriptor); }
  assert.equal(result.state, "selected", "IS_FROZEN_CAPTURE_MUST_SURVIVE_HOSTILE_CALLER_READ");
});
test("Object.isFrozen capture semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "const isFrozen: typeof Object.isFrozen = Object.isFrozen;", replacement = "const isFrozen: typeof Object.isFrozen = (value) => Object.isFrozen(value);", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, replacement); assert.equal(original.split(anchor).length - 1, 1, "IS_FROZEN_CAPTURE_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "IS_FROZEN_CAPTURE_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-is-frozen-capture-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${isFrozenContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${isFrozenMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(isFrozenContract)).length, 1); assert.equal(lines.filter((line) => line.includes("IS_FROZEN_CAPTURE_MUST_SURVIVE_HOSTILE_CALLER_READ")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const isSafeIntegerContract = "finite batch plan position captures Number.isSafeInteger before hostile caller reads", isSafeIntegerMarker = "FINITE_BATCH_PLAN_POSITION_IS_SAFE_INTEGER_CAPTURE_CONTRACT_EXECUTED";
test(isSafeIntegerContract, async () => {
  console.log(isSafeIntegerMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); const descriptor = safeGetOwnPropertyDescriptor(Number, "isSafeInteger"), samples = [0]; let result;
  safeDefineProperty(samples, "0", { configurable: true, enumerable: true, get() { safeDefineProperty(Number, "isSafeInteger", { ...descriptor, value: () => { throw new Error("poisoned"); } }); return 0; } });
  try { assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, samples); }, "IS_SAFE_INTEGER_CAPTURE_MUST_SURVIVE_HOSTILE_CALLER_READ"); } finally { safeDefineProperty(Number, "isSafeInteger", descriptor); }
  assert.equal(result.state, "selected", "IS_SAFE_INTEGER_CAPTURE_MUST_SURVIVE_HOSTILE_CALLER_READ");
});
test("Number.isSafeInteger capture semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "const isSafeInteger: typeof Number.isSafeInteger = Number.isSafeInteger;", replacement = "const isSafeInteger: typeof Number.isSafeInteger = (value) => Number.isSafeInteger(value);", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, replacement); assert.equal(original.split(anchor).length - 1, 1, "IS_SAFE_INTEGER_CAPTURE_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "IS_SAFE_INTEGER_CAPTURE_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-is-safe-integer-capture-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${isSafeIntegerContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${isSafeIntegerMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(isSafeIntegerContract)).length, 1); assert.equal(lines.filter((line) => line.includes("IS_SAFE_INTEGER_CAPTURE_MUST_SURVIVE_HOSTILE_CALLER_READ")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const weakSetHasContract = "finite batch plan position captures shared WeakSet has for plan and successor-state freshness", weakSetHasMarker = "FINITE_BATCH_PLAN_POSITION_WEAK_SET_HAS_CAPTURE_CONTRACT_EXECUTED";
test(weakSetHasContract, async () => {
  console.log(weakSetHasMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); const descriptor = safeGetOwnPropertyDescriptor(WeakSet.prototype, "has"), samples = [0]; let calls = 0, result;
  safeDefineProperty(samples, "0", { configurable: true, enumerable: true, get() { safeDefineProperty(WeakSet.prototype, "has", { ...descriptor, value: function (value) { if (++calls === 2) throw new Error("poisoned"); return safeWeakSetHas(this, value); } }); return 0; } });
  try { assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, samples); }, "SHARED_WEAK_SET_HAS_CAPTURE_MUST_SURVIVE_SECOND_SET_POISON"); } finally { safeDefineProperty(WeakSet.prototype, "has", descriptor); }
  assert.equal(result.state, "selected", "SHARED_WEAK_SET_HAS_CAPTURE_MUST_SURVIVE_SECOND_SET_POISON"); assert.equal(calls, 0, "SHARED_WEAK_SET_HAS_CAPTURE_MUST_SURVIVE_SECOND_SET_POISON");
});
test("shared WeakSet has capture semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "const weakSetHas = Function.prototype.call.bind(WeakSet.prototype.has) as (\n  set: WeakSet<object>, value: object\n) => boolean;", replacement = "const weakSetHas = ((set: WeakSet<object>, value: object) => WeakSet.prototype.has.call(set, value)) as (\n  set: WeakSet<object>, value: object\n) => boolean;", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, replacement); assert.equal(original.split(anchor).length - 1, 1, "WEAK_SET_HAS_CAPTURE_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "WEAK_SET_HAS_CAPTURE_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-weak-set-has-capture-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${weakSetHasContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${weakSetHasMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(weakSetHasContract)).length, 1); assert.equal(lines.filter((line) => line.includes("SHARED_WEAK_SET_HAS_CAPTURE_MUST_SURVIVE_SECOND_SET_POISON")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const weakSetAddContract = "finite batch plan position captures shared WeakSet add for plan and successor-state freshness", weakSetAddMarker = "FINITE_BATCH_PLAN_POSITION_WEAK_SET_ADD_CAPTURE_CONTRACT_EXECUTED";
test(weakSetAddContract, async () => {
  console.log(weakSetAddMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); const descriptor = safeGetOwnPropertyDescriptor(WeakSet.prototype, "add"), samples = [0]; let calls = 0, result;
  safeDefineProperty(samples, "0", { configurable: true, enumerable: true, get() { safeDefineProperty(WeakSet.prototype, "add", { ...descriptor, value: function (value) { if (++calls === 2) throw new Error("poisoned"); return safeWeakSetAdd(this, value); } }); return 0; } });
  try { assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, samples); }, "SHARED_WEAK_SET_ADD_CAPTURE_MUST_SURVIVE_SECOND_SET_POISON"); } finally { safeDefineProperty(WeakSet.prototype, "add", descriptor); }
  assert.equal(result.state, "selected", "SHARED_WEAK_SET_ADD_CAPTURE_MUST_SURVIVE_SECOND_SET_POISON"); assert.equal(calls, 0, "SHARED_WEAK_SET_ADD_CAPTURE_MUST_SURVIVE_SECOND_SET_POISON");
});
test("shared WeakSet add capture semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "const weakSetAdd = Function.prototype.call.bind(WeakSet.prototype.add) as (\n  set: WeakSet<object>, value: object\n) => WeakSet<object>;", replacement = "const weakSetAdd = ((set: WeakSet<object>, value: object) => WeakSet.prototype.add.call(set, value)) as (\n  set: WeakSet<object>, value: object\n) => WeakSet<object>;", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, replacement); assert.equal(original.split(anchor).length - 1, 1, "WEAK_SET_ADD_CAPTURE_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "WEAK_SET_ADD_CAPTURE_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-weak-set-add-capture-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${weakSetAddContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${weakSetAddMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(weakSetAddContract)).length, 1); assert.equal(lines.filter((line) => line.includes("SHARED_WEAK_SET_ADD_CAPTURE_MUST_SURVIVE_SECOND_SET_POISON")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});
