import assert from "node:assert/strict";
import { Buffer } from "node:buffer";
import { spawnSync } from "node:child_process";
import { copyFileSync, mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import test from "node:test";
import { UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END, mapUnsigned32SampleBatchToBoundedTicket } from "@draft-table/engine";
import { fictionalCollationCapabilities } from "./fictional-collation-capabilities.mjs";

const moduleKey = "DRAFT_TABLE_TEST_FINITE_BATCH_PLAN_POSITION_TRANSITION_MODULE";

const needMoreContract = "finite batch plan position need-more cannot select remove or register", needMoreMarker = "FINITE_BATCH_PLAN_POSITION_NEED_MORE_CONTRACT_EXECUTED";
test(needMoreContract, async () => {
  console.log(needMoreMarker);
  const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl);
  const [transition, finite, pack, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]);
  const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected");
  const state = pack.readOmensPackCollationPlanPoolDrawStateForTransition(initialized.plan), position = pack.readOmensPackCollationPlanLayoutForTransition(initialized.plan).slots[0], pool = state.poolStates.find((entry) => entry.poolReference === position.resolvedPool), retry = UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END - UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END % pool.poolTotalWeight;
  let selected = 0, removed = 0, registered = 0, result;
  assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatchForTest(initialized.plan, [retry], mapUnsigned32SampleBatchToBoundedTicket, () => { selected++; throw new Error("NEED_MORE_MUST_NOT_SELECT_REMOVE_OR_REGISTER"); }, () => { removed++; throw new Error("NEED_MORE_MUST_NOT_SELECT_REMOVE_OR_REGISTER"); }, () => { registered++; throw new Error("NEED_MORE_MUST_NOT_SELECT_REMOVE_OR_REGISTER"); }); }, "NEED_MORE_MUST_NOT_SELECT_REMOVE_OR_REGISTER");
  assert.deepEqual(result, { state: "needs-sample", consumedSamples: 1 }, "NEED_MORE_MUST_NOT_SELECT_REMOVE_OR_REGISTER"); assert.equal(selected + removed + registered, 0, "NEED_MORE_MUST_NOT_SELECT_REMOVE_OR_REGISTER"); assert.equal(pack.readOmensPackCollationPlanNextPositionForTransition(initialized.plan), 0, "NEED_MORE_MUST_NOT_SELECT_REMOVE_OR_REGISTER");
});
test("need-more no-side-effect semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = 'if (mapping.state === "needs-sample") return needsSample(mapping.consumedSamples);', original = readFileSync(sourcePath, "utf8");
  const mutated = original.replace(anchor, 'if (mapping.state === "needs-sample") { const injectedIdentity = selectIdentity(current.poolDrawState, poolReference, 0) as OfficialIdentityReference; const injectedState = removeIdentity(current.poolDrawState, poolReference, injectedIdentity) as OmensPackLocalPoolDrawState; registerPlan(plan, positionReference, injectedIdentity, injectedState); return needsSample(mapping.consumedSamples); }');
  assert.equal(original.split(anchor).length - 1, 1, "NEED_MORE_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "NEED_MORE_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-need-more-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${needMoreContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${needMoreMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(needMoreContract)).length, 1); assert.equal(lines.filter((line) => line.includes("NEED_MORE_MUST_NOT_SELECT_REMOVE_OR_REGISTER")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const ticketContract = "finite batch plan position passes accepted ticket unchanged", ticketMarker = "FINITE_BATCH_PLAN_POSITION_TICKET_CONTRACT_EXECUTED";
test(ticketContract, async () => {
  console.log(ticketMarker);
  const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl);
  const [transition, finite, pack, stateModule, selector, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("pack-local-pool-draw-state.ts", directory)), import(new URL("pack-local-pool-ticket-selection.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]);
  const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); const drawState = pack.readOmensPackCollationPlanPoolDrawStateForTransition(initialized.plan), poolReference = pack.readOmensPackCollationPlanLayoutForTransition(initialized.plan).slots[0].resolvedPool, pool = drawState.poolStates.find((entry) => entry.poolReference === poolReference), ticket = pool.officialIdentityChoices[0].cumulativeExclusiveEnd - 1; let result;
  assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatchForTest(initialized.plan, [ticket], mapUnsigned32SampleBatchToBoundedTicket, selector.selectOmensPackLocalPoolOfficialIdentityByTicket, stateModule.removeOmensPackLocalPoolOfficialIdentity, pack.registerOmensPackCollationPlanPositionTransition); }, "ACCEPTED_TICKET_MUST_PASS_UNCHANGED"); assert.equal(result.officialIdentityReference, pool.officialIdentityChoices[0].officialIdentityReference, "ACCEPTED_TICKET_MUST_PASS_UNCHANGED");
});
test("accepted-ticket semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "selectIdentity(current.poolDrawState, poolReference, mapping.ticket)", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, "selectIdentity(current.poolDrawState, poolReference, mapping.ticket + 1)"); assert.equal(original.split(anchor).length - 1, 1, "TICKET_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "TICKET_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-ticket-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${ticketContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${ticketMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(ticketContract)).length, 1); assert.equal(lines.filter((line) => line.includes("ACCEPTED_TICKET_MUST_PASS_UNCHANGED")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const consumedContract = "finite batch plan position preserves engine consumed count", consumedMarker = "FINITE_BATCH_PLAN_POSITION_CONSUMED_CONTRACT_EXECUTED";
test(consumedContract, async () => {
  console.log(consumedMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, pack, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); const state = pack.readOmensPackCollationPlanPoolDrawStateForTransition(initialized.plan), pool = state.poolStates.find((entry) => entry.poolReference === initialized.layoutReference.slots[0].resolvedPool), retry = UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END - UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END % pool.poolTotalWeight, result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [retry, 0]); assert.equal(result.consumedSamples, 2, "ENGINE_CONSUMED_COUNT_MUST_PASS_UNCHANGED");
});
test("consumed-count semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "mapping.consumedSamples, positionReference, officialIdentityReference, nextPlan", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, "0, positionReference, officialIdentityReference, nextPlan"); assert.equal(original.split(anchor).length - 1, 1, "CONSUMED_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "CONSUMED_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-consumed-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${consumedContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${consumedMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(consumedContract)).length, 1); assert.equal(lines.filter((line) => line.includes("ENGINE_CONSUMED_COUNT_MUST_PASS_UNCHANGED")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const positionContract = "finite batch plan transition uses exact current position and resolved pool", positionMarker = "FINITE_BATCH_PLAN_POSITION_SCOPE_CONTRACT_EXECUTED";
test(positionContract, async () => {
  console.log(positionMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, pack, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); let plan = initialized.plan; for (let index = 0; index < 3; index++) plan = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(plan, [0]).nextPlan; let result; assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(plan, [0]); }, "CURRENT_POSITION_AND_RESOLVED_POOL_MUST_BE_EXACT"); assert.equal(result.positionReference, initialized.layoutReference.slots[3], "CURRENT_POSITION_AND_RESOLVED_POOL_MUST_BE_EXACT");
});
test("current-position resolved-pool semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "const poolReference = positionReference.resolvedPool;", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, "const poolReference = current.poolDrawState.poolStates[0].poolReference;"); assert.equal(original.split(anchor).length - 1, 1, "POSITION_SCOPE_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "POSITION_SCOPE_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-scope-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${positionContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${positionMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(positionContract)).length, 1); assert.equal(lines.filter((line) => line.includes("CURRENT_POSITION_AND_RESOLVED_POOL_MUST_BE_EXACT")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const removalContract = "finite batch plan transition removes exact selected identity from same pool only", removalMarker = "FINITE_BATCH_PLAN_POSITION_REMOVAL_CONTRACT_EXECUTED";
test(removalContract, async () => {
  console.log(removalMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, pack, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); const prior = pack.readOmensPackCollationPlanPoolDrawStateForTransition(initialized.plan), selectedPool = prior.poolStates[0], untouched = prior.poolStates[8]; let result; assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]); }, "EXACT_IDENTITY_SAME_POOL_ONLY_REMOVAL_REQUIRED"); const next = pack.readOmensPackCollationPlanPoolDrawStateForTransition(result.nextPlan); assert.equal(next.poolStates[0].officialIdentityChoices.some((choice) => choice.officialIdentityReference === result.officialIdentityReference), false, "EXACT_IDENTITY_SAME_POOL_ONLY_REMOVAL_REQUIRED"); assert.notEqual(next.poolStates[0], selectedPool, "EXACT_IDENTITY_SAME_POOL_ONLY_REMOVAL_REQUIRED"); assert.equal(next.poolStates[8], untouched, "EXACT_IDENTITY_SAME_POOL_ONLY_REMOVAL_REQUIRED");
});
test("selected-identity same-pool removal semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "current.poolDrawState, poolReference, officialIdentityReference\n  ) as OmensPackLocalPoolDrawState;", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, "current.poolDrawState, current.poolDrawState.poolStates[8].poolReference, current.poolDrawState.poolStates[8].officialIdentityChoices[0].officialIdentityReference\n  ) as OmensPackLocalPoolDrawState;"); assert.equal(original.split(anchor).length - 1, 1, "REMOVAL_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "REMOVAL_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-removal-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${removalContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${removalMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(removalContract)).length, 1); assert.equal(lines.filter((line) => line.includes("EXACT_IDENTITY_SAME_POOL_ONLY_REMOVAL_REQUIRED")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const cursorContract = "finite batch plan transition advances cursor exactly one", cursorMarker = "FINITE_BATCH_PLAN_POSITION_CURSOR_CONTRACT_EXECUTED";
test(cursorContract, async () => {
  console.log(cursorMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, pack, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); let result; assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]); }, "CURSOR_MUST_ADVANCE_EXACTLY_ONE"); assert.equal(pack.readOmensPackCollationPlanNextPositionForTransition(result.nextPlan), 1, "CURSOR_MUST_ADVANCE_EXACTLY_ONE");
});
test("cursor increment semantic mutation fails its exact named contract", () => {
  const transitionPath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), planPath = new URL("../src/pack-collation-plan.ts", import.meta.url), anchor = "nextPosition: prior.nextPosition + 1", original = readFileSync(planPath, "utf8"), mutated = original.replace(anchor, "nextPosition: prior.nextPosition + 2"); assert.equal(original.split(anchor).length - 1, 1, "CURSOR_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "CURSOR_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-cursor-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "pack-collation-plan.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, fileURLToPath(transitionPath).split("/").at(-1))).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${cursorContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${cursorMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(cursorContract)).length, 1); assert.equal(lines.filter((line) => line.includes("CURSOR_MUST_ADVANCE_EXACTLY_ONE")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const historyContract = "finite batch plan transition does not mutate or reuse old plan", historyMarker = "FINITE_BATCH_PLAN_POSITION_HISTORY_CONTRACT_EXECUTED";
test(historyContract, async () => {
  console.log(historyMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, pack, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); const oldState = pack.readOmensPackCollationPlanPoolDrawStateForTransition(initialized.plan), result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]); assert.notEqual(result.nextPlan, initialized.plan, "OLD_PLAN_MUST_NOT_BE_MUTATED_OR_REUSED"); assert.equal(pack.readOmensPackCollationPlanNextPositionForTransition(initialized.plan), 0, "OLD_PLAN_MUST_NOT_BE_MUTATED_OR_REUSED"); assert.equal(pack.readOmensPackCollationPlanPoolDrawStateForTransition(initialized.plan), oldState, "OLD_PLAN_MUST_NOT_BE_MUTATED_OR_REUSED");
});
test("old-plan reuse semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "mapping.consumedSamples, positionReference, officialIdentityReference, nextPlan\n  );", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, "mapping.consumedSamples, positionReference, officialIdentityReference, plan\n  );"); assert.equal(original.split(anchor).length - 1, 1, "HISTORY_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "HISTORY_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-history-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${historyContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${historyMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(historyContract)).length, 1); assert.equal(lines.filter((line) => line.includes("OLD_PLAN_MUST_NOT_BE_MUTATED_OR_REUSED")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const retentionContract = "finite batch plan transition retains exact layout and compiled capability", retentionMarker = "FINITE_BATCH_PLAN_POSITION_RETENTION_CONTRACT_EXECUTED";
test(retentionContract, async () => {
  console.log(retentionMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, pack, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); let result; assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]); }, "NEXT_PLAN_MUST_RETAIN_EXACT_LAYOUT_AND_CAPABILITY"); assert.equal(pack.readOmensPackCollationPlanLayoutForTransition(result.nextPlan), initialized.layoutReference, "NEXT_PLAN_MUST_RETAIN_EXACT_LAYOUT_AND_CAPABILITY"); assert.equal(pack.readOmensPackCollationPlanTablesForTest(result.nextPlan), tables, "NEXT_PLAN_MUST_RETAIN_EXACT_LAYOUT_AND_CAPABILITY");
});
test("next-plan layout-capability retention semantic mutation fails its exact named contract", () => {
  const transitionPath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), planPath = new URL("../src/pack-collation-plan.ts", import.meta.url), anchor = "layoutReference: prior.layoutReference,", original = readFileSync(planPath, "utf8"), mutated = original.replace(anchor, "layoutReference: prior.tables.layoutChoices[1].layoutReference,"); assert.equal(original.split(anchor).length - 1, 1, "RETENTION_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "RETENTION_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-retention-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "pack-collation-plan.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, fileURLToPath(transitionPath).split("/").at(-1))).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${retentionContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${retentionMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(retentionContract)).length, 1); assert.equal(lines.filter((line) => line.includes("NEXT_PLAN_MUST_RETAIN_EXACT_LAYOUT_AND_CAPABILITY")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const freshnessContract = "finite batch plan position rejects previously handed-out sibling plan", freshnessMarker = "FINITE_BATCH_PLAN_POSITION_FRESHNESS_CONTRACT_EXECUTED";
test(freshnessContract, async () => {
  console.log(freshnessMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, pack, stateModule, selector, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("pack-local-pool-draw-state.ts", directory)), import(new URL("pack-local-pool-ticket-selection.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); const sibling = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]); assert.equal(sibling.state, "selected"); const siblingState = pack.readOmensPackCollationPlanPoolDrawStateForTransition(sibling.nextPlan); assert.throws(() => transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatchForTest(initialized.plan, [0], mapUnsigned32SampleBatchToBoundedTicket, selector.selectOmensPackLocalPoolOfficialIdentityByTicket, () => siblingState, () => sibling.nextPlan), { code: "OMENS_PACK_COLLATION_PLAN_POSITION_TRANSITION_FAILED" }, "HANDED_OUT_SIBLING_PLAN_MUST_NOT_BE_REUSED");
});
test("transition-plan freshness semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = ") || hasHandedOutTransitionPlan(nextPlan)) return fail();", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, ") || false) return fail();"); assert.equal(original.split(anchor).length - 1, 1, "FRESHNESS_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "FRESHNESS_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-freshness-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${freshnessContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${freshnessMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(freshnessContract)).length, 1); assert.equal(lines.filter((line) => line.includes("HANDED_OUT_SIBLING_PLAN_MUST_NOT_BE_REUSED")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const acceptedCountContract = "finite batch plan position accepted count cannot exceed captured batch", acceptedCountMarker = "FINITE_BATCH_PLAN_POSITION_ACCEPTED_COUNT_CONTRACT_EXECUTED";
test(acceptedCountContract, async () => {
  console.log(acceptedCountMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, stateModule, selector, pack, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-local-pool-draw-state.ts", directory)), import(new URL("pack-local-pool-ticket-selection.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); assert.throws(() => transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatchForTest(initialized.plan, [0], () => Object.freeze({ state: "accepted", ticket: 0, consumedSamples: 2 }), selector.selectOmensPackLocalPoolOfficialIdentityByTicket, stateModule.removeOmensPackLocalPoolOfficialIdentity, pack.registerOmensPackCollationPlanPositionTransition), { code: "OMENS_PACK_COLLATION_PLAN_POSITION_TRANSITION_FAILED" }, "ACCEPTED_COUNT_MUST_NOT_EXCEED_CAPTURED_BATCH");
});
test("accepted-count upper-bound semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "consumedSamples < 1 || consumedSamples > sampleCount", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, "consumedSamples < 1 || false"); assert.equal(original.split(anchor).length - 1, 1, "ACCEPTED_COUNT_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "ACCEPTED_COUNT_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-accepted-count-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${acceptedCountContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${acceptedCountMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(acceptedCountContract)).length, 1); assert.equal(lines.filter((line) => line.includes("ACCEPTED_COUNT_MUST_NOT_EXCEED_CAPTURED_BATCH")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const needsCountContract = "finite batch plan position needs count equals captured batch", needsCountMarker = "FINITE_BATCH_PLAN_POSITION_NEEDS_COUNT_CONTRACT_EXECUTED";
test(needsCountContract, async () => {
  console.log(needsCountMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); assert.throws(() => transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatchForTest(initialized.plan, [0], () => Object.freeze({ state: "needs-sample", consumedSamples: 0 }), () => { throw new Error("must not select"); }, () => { throw new Error("must not remove"); }, () => { throw new Error("must not register"); }), { code: "OMENS_PACK_COLLATION_PLAN_POSITION_TRANSITION_FAILED" }, "NEEDS_COUNT_MUST_EQUAL_CAPTURED_BATCH");
});
test("needs-count equality semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "if (consumedSamples !== sampleCount) return fail();", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, "if (false) return fail();"); assert.equal(original.split(anchor).length - 1, 1, "NEEDS_COUNT_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "NEEDS_COUNT_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-needs-count-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${needsCountContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${needsCountMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(needsCountContract)).length, 1); assert.equal(lines.filter((line) => line.includes("NEEDS_COUNT_MUST_EQUAL_CAPTURED_BATCH")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const callerSnapshotContract = "finite batch plan position snapshots caller batch once before mapping", callerSnapshotMarker = "FINITE_BATCH_PLAN_POSITION_CALLER_SNAPSHOT_CONTRACT_EXECUTED";
test(callerSnapshotContract, async () => {
  console.log(callerSnapshotMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, stateModule, selector, pack, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-local-pool-draw-state.ts", directory)), import(new URL("pack-local-pool-ticket-selection.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler });
  for (const useSeam of [false, true]) { const initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); let lengthReads = 0, elementReads = 0; const samples = new Proxy([0], { get(target, property, receiver) { if (property === "length") return ++lengthReads === 1 ? 1 : 0; if (property === "0") elementReads++; return Reflect.get(target, property, receiver); } }); let result; assert.doesNotThrow(() => { result = useSeam ? transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatchForTest(initialized.plan, samples, mapUnsigned32SampleBatchToBoundedTicket, selector.selectOmensPackLocalPoolOfficialIdentityByTicket, stateModule.removeOmensPackLocalPoolOfficialIdentity, pack.registerOmensPackCollationPlanPositionTransition) : transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, samples); }, "CALLER_BATCH_MUST_BE_SNAPSHOTTED_BEFORE_MAPPING"); assert.equal(result.state, "selected", "CALLER_BATCH_MUST_BE_SNAPSHOTTED_BEFORE_MAPPING"); assert.equal(result.consumedSamples, 1, "CALLER_BATCH_MUST_BE_SNAPSHOTTED_BEFORE_MAPPING"); assert.equal(lengthReads, 1, "CALLER_BATCH_MUST_BE_SNAPSHOTTED_BEFORE_MAPPING"); assert.equal(elementReads, 1, "CALLER_BATCH_MUST_BE_SNAPSHOTTED_BEFORE_MAPPING"); }
});
test("caller-batch snapshot semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "plan, batch.samples, batch.sampleCount, mapBatch, selectIdentity, removeIdentity, registerPlan", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, "plan, batchInput as readonly number[], batch.sampleCount, mapBatch, selectIdentity, removeIdentity, registerPlan"); assert.equal(original.split(anchor).length - 1, 1, "CALLER_SNAPSHOT_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "CALLER_SNAPSHOT_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-caller-snapshot-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${callerSnapshotContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${callerSnapshotMarker}`).length, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(callerSnapshotContract)).length, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line.includes("CALLER_BATCH_MUST_BE_SNAPSHOTTED_BEFORE_MAPPING")).length, 1, `${result.stdout}\n${result.stderr}`); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const prototypeIndexContract = "finite batch plan position snapshot survives poisoned Array prototype index zero", prototypeIndexMarker = "FINITE_BATCH_PLAN_POSITION_PROTOTYPE_INDEX_CONTRACT_EXECUTED";
test(prototypeIndexContract, async () => {
  console.log(prototypeIndexMarker);
  const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl);
  const [transition, finite, stateModule, selector, pack, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("pack-local-pool-draw-state.ts", directory)), import(new URL("pack-local-pool-ticket-selection.ts", directory)), import(new URL("pack-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]);
  const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected");
  const drawState = pack.readOmensPackCollationPlanPoolDrawStateForTransition(initialized.plan), poolReference = initialized.layoutReference.slots[0].resolvedPool, pool = drawState.poolStates.find((entry) => entry.poolReference === poolReference), sample = pool.officialIdentityChoices[0].cumulativeExclusiveEnd - 1, poisonedSample = pool.poolTotalWeight - 1, expectedIdentity = selector.selectOmensPackLocalPoolOfficialIdentityByTicket(drawState, poolReference, sample), caller = [sample], priorDescriptor = Object.getOwnPropertyDescriptor(Array.prototype, "0");
  let inheritedGets = 0, inheritedSets = 0, mappedTicket, snapshotDescriptor, snapshotReference, result, thrown, restored;
  const mapper = (samples, bound) => { snapshotReference = samples; snapshotDescriptor = Object.getOwnPropertyDescriptor(samples, "0"); const mapping = mapUnsigned32SampleBatchToBoundedTicket(samples, bound); if (mapping.state === "accepted") mappedTicket = mapping.ticket; return mapping; };
  try {
    Object.defineProperty(Array.prototype, "0", { configurable: true, enumerable: false, get() { inheritedGets++; return poisonedSample; }, set() { inheritedSets++; } });
    try { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatchForTest(initialized.plan, caller, mapper, selector.selectOmensPackLocalPoolOfficialIdentityByTicket, stateModule.removeOmensPackLocalPoolOfficialIdentity, pack.registerOmensPackCollationPlanPositionTransition); } catch (error) { thrown = error; }
  } finally {
    restored = priorDescriptor === undefined ? Reflect.deleteProperty(Array.prototype, "0") : (Object.defineProperty(Array.prototype, "0", priorDescriptor), true);
  }
  assert.equal(thrown, undefined, "PROTOTYPE_INDEX_ZERO_MUST_NOT_INTERCEPT_BOUNDARY_SNAPSHOT");
  assert.equal(restored, true, "PROTOTYPE_INDEX_ZERO_MUST_NOT_INTERCEPT_BOUNDARY_SNAPSHOT");
  assert.deepEqual(Object.getOwnPropertyDescriptor(Array.prototype, "0"), priorDescriptor, "PROTOTYPE_INDEX_ZERO_MUST_NOT_INTERCEPT_BOUNDARY_SNAPSHOT");
  assert.notEqual(snapshotReference, caller, "PROTOTYPE_INDEX_ZERO_MUST_NOT_INTERCEPT_BOUNDARY_SNAPSHOT");
  assert.deepEqual(snapshotDescriptor, { value: sample, writable: false, enumerable: true, configurable: false }, "PROTOTYPE_INDEX_ZERO_MUST_NOT_INTERCEPT_BOUNDARY_SNAPSHOT");
  assert.equal(inheritedGets, 0, "PROTOTYPE_INDEX_ZERO_MUST_NOT_INTERCEPT_BOUNDARY_SNAPSHOT"); assert.equal(inheritedSets, 0, "PROTOTYPE_INDEX_ZERO_MUST_NOT_INTERCEPT_BOUNDARY_SNAPSHOT");
  assert.equal(mappedTicket, sample, "PROTOTYPE_INDEX_ZERO_MUST_NOT_INTERCEPT_BOUNDARY_SNAPSHOT"); assert.equal(result.state, "selected", "PROTOTYPE_INDEX_ZERO_MUST_NOT_INTERCEPT_BOUNDARY_SNAPSHOT"); assert.equal(result.officialIdentityReference, expectedIdentity, "PROTOTYPE_INDEX_ZERO_MUST_NOT_INTERCEPT_BOUNDARY_SNAPSHOT");
});
test("prototype index-zero snapshot-write semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "    defineOwnDataProperty(sampleSnapshot, String(index), {\n      value: batchInput[index], writable: false, enumerable: true, configurable: false\n    });", replacement = "    sampleSnapshot.push(batchInput[index]);", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, replacement);
  assert.equal(original.split(anchor).length - 1, 1, "PROTOTYPE_INDEX_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "PROTOTYPE_INDEX_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-prototype-index-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${prototypeIndexContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${prototypeIndexMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(prototypeIndexContract)).length, 1); assert.equal(lines.filter((line) => line.includes("PROTOTYPE_INDEX_ZERO_MUST_NOT_INTERCEPT_BOUNDARY_SNAPSHOT")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const arrayGuardContract = "finite batch plan position captures Array.isArray before hostile calls", arrayGuardMarker = "FINITE_BATCH_PLAN_POSITION_ARRAY_IS_ARRAY_CONTRACT_EXECUTED";
test(arrayGuardContract, async () => {
  console.log(arrayGuardMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); const original = Array.isArray; let result; try { Array.isArray = () => { throw new Error("poisoned"); }; assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]); }, "ARRAY_IS_ARRAY_CAPTURE_MUST_SURVIVE_HOSTILE_CALL"); } finally { Array.isArray = original; } assert.equal(result.state, "selected", "ARRAY_IS_ARRAY_CAPTURE_MUST_SURVIVE_HOSTILE_CALL");
});
test("Array.isArray capture semantic mutation fails its exact named contract", () => {
  const sourcePath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), anchor = "const isArray: typeof Array.isArray = Array.isArray;", replacement = "const isArray = ((value: unknown) => Array.isArray(value)) as typeof Array.isArray;", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, replacement); assert.equal(original.split(anchor).length - 1, 1, "ARRAY_IS_ARRAY_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "ARRAY_IS_ARRAY_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-array-is-array-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "finite-batch-plan-position-transition.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "finite-batch-plan-position-transition.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${arrayGuardContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${arrayGuardMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(arrayGuardContract)).length, 1); assert.equal(lines.filter((line) => line.includes("ARRAY_IS_ARRAY_CAPTURE_MUST_SURVIVE_HOSTILE_CALL")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const terminalContract = "finite batch plan position terminal cursor rejects before mapping", terminalMarker = "FINITE_BATCH_PLAN_POSITION_TERMINAL_CONTRACT_EXECUTED";
test(terminalContract, async () => {
  console.log(terminalMarker); const moduleUrl = process.env[moduleKey] ?? new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url).href, directory = new URL("./", moduleUrl); const [transition, finite, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]); const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); assert.equal(initialized.state, "selected"); let plan = initialized.plan; for (let index = 0; index < 14; index++) plan = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(plan, [0]).nextPlan; assert.throws(() => transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(plan, []), { code: "OMENS_PACK_COLLATION_PLAN_POSITION_TRANSITION_FAILED" }, "TERMINAL_CURSOR_MUST_REJECT_BEFORE_MAPPING");
});
test("terminal-cursor semantic mutation fails its exact named contract", () => {
  const transitionPath = new URL("../src/finite-batch-plan-position-transition.ts", import.meta.url), planPath = new URL("../src/pack-collation-plan.ts", import.meta.url), anchor = "  if (!isSafeInteger(parts.nextPosition) || parts.nextPosition < 0 ||\n    parts.nextPosition >= EXPECTED_POSITION_COUNT) return fail();\n  const positionReference = parts.layoutReference.slots[parts.nextPosition];\n  if (positionReference === undefined || !isFrozen(positionReference) ||\n    positionReference.position !== parts.nextPosition + 1) return fail();", replacement = "  if (!isSafeInteger(parts.nextPosition) || parts.nextPosition < 0 ||\n    parts.nextPosition > EXPECTED_POSITION_COUNT) return fail();\n  const positionReference = parts.layoutReference.slots[parts.nextPosition] ?? parts.layoutReference.slots[0];\n  if (!isFrozen(positionReference)) return fail();", original = readFileSync(planPath, "utf8"), mutated = original.replace(anchor, replacement); assert.equal(original.split(anchor).length - 1, 1, "TERMINAL_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "TERMINAL_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-position-terminal-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "pack-collation-plan.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, fileURLToPath(transitionPath).split("/").at(-1))).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${terminalContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${terminalMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(terminalContract)).length, 1); assert.equal(lines.filter((line) => line.includes("TERMINAL_CURSOR_MUST_REJECT_BEFORE_MAPPING")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});
