import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { copyFileSync, mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import test from "node:test";
import { mapUnsigned32SampleBatchToBoundedTicket } from "@draft-table/engine";
import { fictionalCollationCapabilities } from "./fictional-collation-capabilities.mjs";
import { initializeOmensPackCollationPlanFromUnsigned32SampleBatch, OmensPackCollationPlanInitializationError } from "../src/schema-validation.ts";
import { initializeOmensPackCollationPlanFromUnsigned32SampleBatchForTest } from "../src/finite-batch-collation-plan.ts";

const publicModuleKey = "DRAFT_TABLE_TEST_FINITE_BATCH_PUBLIC_MODULE";
const seamModuleKey = "DRAFT_TABLE_TEST_FINITE_BATCH_SEAM_MODULE";
const finitePath = new URL("../src/finite-batch-collation-plan.ts", import.meta.url);
const schemaPath = new URL("../src/schema-validation.ts", import.meta.url);
const exactPattern = (name) => `^${name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`;
const exactPlanError = (error) => error instanceof OmensPackCollationPlanInitializationError && error.code === "OMENS_PACK_COLLATION_PLAN_INITIALIZATION_FAILED" && error.name === "OmensPackCollationPlanInitializationError";
const revoked = () => { const handle = Proxy.revocable([], {}); handle.revoke(); return handle.proxy; };
const revokeDuringIndexRead = () => { const handle = Proxy.revocable([0], { get(target, property, receiver) { if (property === "0") { handle.revoke(); return 0; } return Reflect.get(target, property, receiver); } }); return handle.proxy; };

test("public finite batch revoked-before-call rejects only with the stable plan error and mid-read revocation selects once", () => {
  const { tables } = fictionalCollationCapabilities();
  assert.throws(() => initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, revoked()), exactPlanError, "PUBLIC_REVOKED_PROXY_MUST_USE_PLAN_ERROR");
  const result = initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, revokeDuringIndexRead());
  assert.equal(result.state, "selected"); assert.equal(result.consumedSamples, 1, "PUBLIC_MID_READ_REVOCATION_MUST_USE_SNAPSHOTTED_SAMPLE");
});

test("test-seam finite batch revoked-before-call rejects only with the stable plan error and mid-read revocation selects once", () => {
  const { tables } = fictionalCollationCapabilities();
  assert.throws(() => initializeOmensPackCollationPlanFromUnsigned32SampleBatchForTest(tables, revoked(), mapUnsigned32SampleBatchToBoundedTicket), exactPlanError, "SEAM_REVOKED_PROXY_MUST_USE_PLAN_ERROR");
  const result = initializeOmensPackCollationPlanFromUnsigned32SampleBatchForTest(tables, revokeDuringIndexRead(), mapUnsigned32SampleBatchToBoundedTicket);
  assert.equal(result.state, "selected"); assert.equal(result.consumedSamples, 1, "SEAM_MID_READ_REVOCATION_MUST_USE_SNAPSHOTTED_SAMPLE");
});

const publicContract = "public finite batch revoked proxy stays inside the stable plan error boundary", publicMarker = "PUBLIC_FINITE_BATCH_REVOKED_PROXY_CONTRACT_EXECUTED";
test(publicContract, async () => { console.log(publicMarker); const moduleUrl = process.env[publicModuleKey] ?? schemaPath.href, directory = new URL("./", moduleUrl), [api, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]), capabilities = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }); assert.throws(() => api.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(capabilities.tables, revoked()), (error) => error instanceof api.OmensPackCollationPlanInitializationError && error.code === "OMENS_PACK_COLLATION_PLAN_INITIALIZATION_FAILED", "PUBLIC_REVOKED_PROXY_MUST_USE_PLAN_ERROR"); });
test("public finite batch revoked proxy boundary mutation fails its exact named contract", () => {
  const anchor = "  try {\n    if (inputs.length !== 2 || !isArray(inputs[1])) return fail();\n    const samples = inputs[1], sampleCount = samples.length;\n    if (!isSafeInteger(sampleCount) || sampleCount < 0 ||\n      sampleCount >= UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END) return fail();", replacement = "  if (inputs.length !== 2 || !isArray(inputs[1])) return fail();\n  const samples = inputs[1], sampleCount = samples.length;\n  if (!isSafeInteger(sampleCount) || sampleCount < 0 ||\n    sampleCount >= UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END) return fail();\n  try {", original = readFileSync(finitePath, "utf8"), mutated = original.replace(anchor, replacement); assert.equal(original.split(anchor).length - 1, 1, "PUBLIC_REVOKED_PROXY_ANCHOR_ONCE"); assert.notEqual(mutated, original, "PUBLIC_REVOKED_PROXY_BYTES_CHANGED"); let directory; try { directory = mkdtempSync(join(tmpdir(), "draft-table-public-revoked-proxy-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((file) => file.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(directory, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(directory, "node_modules"), "dir"); writeFileSync(join(directory, "finite-batch-collation-plan.ts"), mutated); writeFileSync(join(directory, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const typecheck = spawnSync(join(directory, "node_modules", ".bin", "tsc"), ["-p", join(directory, "tsconfig.json")], { encoding: "utf8" }); assert.equal(typecheck.status, 0, typecheck.stdout + "\n" + typecheck.stderr); const environment = { ...process.env, [publicModuleKey]: pathToFileURL(join(directory, "schema-validation.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", exactPattern(publicContract), fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, result.stdout + "\n" + result.stderr); assert.equal(lines.filter((line) => line === `# ${publicMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(publicContract)).length, 1); assert.equal(lines.filter((line) => line.includes("PUBLIC_REVOKED_PROXY_MUST_USE_PLAN_ERROR")).length, 1); } finally { if (directory !== undefined) rmSync(directory, { recursive: true, force: true }); } });

const seamContract = "test seam finite batch revoked proxy stays inside the stable plan error boundary", seamMarker = "SEAM_FINITE_BATCH_REVOKED_PROXY_CONTRACT_EXECUTED";
test(seamContract, async () => { console.log(seamMarker); const moduleUrl = process.env[seamModuleKey] ?? finitePath.href, directory = new URL("./", moduleUrl), [plan, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]), capabilities = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), packPlan = await import(new URL("pack-collation-plan.ts", directory)); assert.throws(() => plan.initializeOmensPackCollationPlanFromUnsigned32SampleBatchForTest(capabilities.tables, revoked(), mapUnsigned32SampleBatchToBoundedTicket), (error) => error instanceof packPlan.OmensPackCollationPlanInitializationError && error.code === "OMENS_PACK_COLLATION_PLAN_INITIALIZATION_FAILED", "SEAM_REVOKED_PROXY_MUST_USE_PLAN_ERROR"); });
test("test seam finite batch revoked proxy boundary mutation fails its exact named contract", () => {
  const anchor = "  try {\n    if (inputs.length !== 3 || !isArray(inputs[1]) || typeof inputs[2] !== \"function\") return fail();\n    const samples = inputs[1], sampleCount = samples.length;\n    if (!isSafeInteger(sampleCount) || sampleCount < 0 ||\n      sampleCount >= UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END) return fail();", replacement = "  if (inputs.length !== 3 || !isArray(inputs[1]) || typeof inputs[2] !== \"function\") return fail();\n  const samples = inputs[1], sampleCount = samples.length;\n  if (!isSafeInteger(sampleCount) || sampleCount < 0 ||\n    sampleCount >= UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END) return fail();\n  try {", original = readFileSync(finitePath, "utf8"), mutated = original.replace(anchor, replacement); assert.equal(original.split(anchor).length - 1, 1, "SEAM_REVOKED_PROXY_ANCHOR_ONCE"); assert.notEqual(mutated, original, "SEAM_REVOKED_PROXY_BYTES_CHANGED"); let directory; try { directory = mkdtempSync(join(tmpdir(), "draft-table-seam-revoked-proxy-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((file) => file.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(directory, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(directory, "node_modules"), "dir"); writeFileSync(join(directory, "finite-batch-collation-plan.ts"), mutated); writeFileSync(join(directory, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const typecheck = spawnSync(join(directory, "node_modules", ".bin", "tsc"), ["-p", join(directory, "tsconfig.json")], { encoding: "utf8" }); assert.equal(typecheck.status, 0, typecheck.stdout + "\n" + typecheck.stderr); const environment = { ...process.env, [seamModuleKey]: pathToFileURL(join(directory, "finite-batch-collation-plan.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", exactPattern(seamContract), fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, result.stdout + "\n" + result.stderr); assert.equal(lines.filter((line) => line === `# ${seamMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.includes(seamContract)).length, 1); assert.equal(lines.filter((line) => line.includes("SEAM_REVOKED_PROXY_MUST_USE_PLAN_ERROR")).length, 1); } finally { if (directory !== undefined) rmSync(directory, { recursive: true, force: true }); } });
