import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

const runner = fileURLToPath(new URL("./pack-collation-plan-evidence-command.mjs", import.meta.url));
const variables = ["OMENS_RECIPE_EVIDENCE_PATH", "FAB_CARD_SOURCE_EVIDENCE_PATH", "FAB_CARD_SCHEMA_EVIDENCE_PATH", "FAB_CARD_VAULT_EVIDENCE_PATH"], name = "four checksum-verified caller-held sources initialize every selected Omens collation layout with a fresh exact all-pool plan", marker = "PACK_COLLATION_PLAN_INITIALIZATION_CONTRACT_EXECUTED", bytes = variables.map((_, index) => `synthetic pack plan command bytes ${index}`);
const passing = `import assert from "node:assert/strict"; import { createHash } from "node:crypto"; import { readFileSync } from "node:fs"; import test from "node:test"; const variables=${JSON.stringify(variables)}, expected=${JSON.stringify(bytes)}, available=variables.every((variable)=>Boolean(process.env[variable])); test(${JSON.stringify(name)}, { skip: !available ? "missing" : false }, () => { assert.equal(process.env.NODE_TEST_CONTEXT.startsWith("child-v"), true); for (const [index, variable] of variables.entries()) assert.equal(createHash("sha256").update(readFileSync(process.env[variable])).digest("hex"), createHash("sha256").update(expected[index]).digest("hex")); console.log(${JSON.stringify(marker)}); });`;
const run = (contract = passing, option = {}) => { const directory = mkdtempSync(join(tmpdir(), "draft-table-pack-collation-plan-command-")), testDirectory = join(directory, "test"); mkdirSync(testDirectory); writeFileSync(join(testDirectory, "probe.pack-collation-plan-evidence.test.mjs"), contract); const environment = { ...process.env, NODE_TEST_CONTEXT: "synthetic-parent-context" }; for (const [index, variable] of variables.entries()) { const path = join(directory, variable); writeFileSync(path, bytes[index]); environment[variable] = path; } if (option.missing) delete environment[option.missing]; if (option.unreadable) environment[option.unreadable] = join(directory, "missing"); if (option.swap) [environment[variables[0]], environment[variables[1]]] = [environment[variables[1]], environment[variables[0]]]; try { return spawnSync(process.execPath, [runner, ...(option.args ?? [])], { cwd: directory, encoding: "utf8", env: environment }); } finally { rmSync(directory, { recursive: true, force: true }); } };
const rejected = (result) => { assert.notEqual(result.status, 0); assert.equal(result.stdout, ""); assert.equal(result.stderr, "Pack collation plan initialization acceptance failed.\n"); };

test("pack collation plan command rejects missing unreadable checksum-wrong and usage inputs", () => { for (const variable of variables) { rejected(run(passing, { missing: variable })); rejected(run(passing, { unreadable: variable })); } rejected(run(passing, { swap: true })); rejected(run(passing, { args: ["unexpected"] })); });
test("pack collation plan command rejects nonexecution arbitrary failure duplicates and wrong marker", () => { rejected(run(`import test from "node:test"; test(${JSON.stringify(name)}, { skip: true }, () => {});`)); rejected(run(passing.replace(marker, "WRONG_MARKER"))); rejected(run(passing.replace(`console.log(${JSON.stringify(marker)});`, `console.log(${JSON.stringify(marker)}); process.exitCode = 29;`))); rejected(run(`${passing}\ntest(${JSON.stringify(name)}, () => console.log(${JSON.stringify(marker)}));`)); });
test("pack collation plan command sanitizes inherited context and prints only its exact success marker", () => { const result = run(); assert.equal(result.status, 0, result.stderr); assert.equal(result.stdout, "pack collation plan initialization acceptance passed\n"); assert.equal(result.stderr, ""); });
