import assert from "node:assert/strict";
import { Buffer } from "node:buffer";
import { spawnSync } from "node:child_process";
import { copyFileSync, mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import test from "node:test";
import { fictionalCollationCapabilities } from "./fictional-collation-capabilities.mjs";

// Task-local hardening inventory: selection-history construction adds no mutable global and
// introduces no new intrinsic capture. It reuses this module's pre-caller Object.defineProperty
// and Object.freeze captures, proved below by isolated live-global substitutions. The existing
// isFrozen/isSafeInteger/arrayEvery/arrayFind/WeakMap captures are only reused for validation and
// are all completed during module evaluation, before an exported call can expose a hostile read.
// Array/object literals do not consult replaceable global constructors; numeric property keys are
// passed as numbers, so the mutable global String is unreachable. Every numeric write is an own
// definition, so inherited indexed setters are unreachable. No earlier module is changed here.
const moduleKey = "DRAFT_TABLE_TEST_PACK_COLLATION_PLAN_SELECTION_HISTORY_HARDENING_MODULE";
const sourcePath = new URL("../src/pack-collation-plan.ts", import.meta.url);

const defineContract = "pack collation plan selection history captures own-property definition before live substitution";
const defineMarker = "PACK_COLLATION_PLAN_SELECTION_HISTORY_DEFINE_PROPERTY_CAPTURE_CONTRACT_EXECUTED";
test(defineContract, async () => {
  console.log(defineMarker);
  const moduleUrl = process.env[moduleKey] ?? sourcePath.href, directory = new URL("./", moduleUrl);
  const [pack, finite, transition, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("finite-batch-plan-position-transition.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]);
  const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]), safeDefine = Object.defineProperty, descriptor = Object.getOwnPropertyDescriptor(Object, "defineProperty"); let result;
  try { safeDefine(Object, "defineProperty", { ...descriptor, value: () => { throw new Error("poisoned live defineProperty"); } }); assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]); }, "SELECTION_HISTORY_DEFINE_PROPERTY_CAPTURE_MUST_SURVIVE_LIVE_SUBSTITUTION"); } finally { safeDefine(Object, "defineProperty", descriptor); }
  const history = pack.readOmensPackCollationPlanSelectionHistoryForCompletion(result.nextPlan), record = history[0];
  assert.deepEqual(Object.getOwnPropertyDescriptor(history, "0"), { value: record, writable: false, enumerable: true, configurable: false }, "SELECTION_HISTORY_DEFINE_PROPERTY_CAPTURE_MUST_SURVIVE_LIVE_SUBSTITUTION");
  assert.deepEqual(Object.getOwnPropertyDescriptor(record, "positionReference"), { value: result.positionReference, writable: false, enumerable: true, configurable: false }, "SELECTION_HISTORY_DEFINE_PROPERTY_CAPTURE_MUST_SURVIVE_LIVE_SUBSTITUTION");
  assert.deepEqual(Object.getOwnPropertyDescriptor(record, "officialIdentityReference"), { value: result.officialIdentityReference, writable: false, enumerable: true, configurable: false }, "SELECTION_HISTORY_DEFINE_PROPERTY_CAPTURE_MUST_SURVIVE_LIVE_SUBSTITUTION");
});
test("selection-history Object.defineProperty live-global mutation fails its exact named contract", () => {
  const anchor = "const defineOwnDataProperty: typeof Object.defineProperty = Object.defineProperty;", replacement = "const defineOwnDataProperty = ((value: object, property: PropertyKey, descriptor: PropertyDescriptor) => globalThis.Object.defineProperty(value, property, descriptor)) as typeof Object.defineProperty;", original = readFileSync(sourcePath, "utf8");
  const mutated = original.replace(anchor, replacement);
  assert.equal(original.split(anchor).length - 1, 1, "SELECTION_HISTORY_DEFINE_PROPERTY_CAPTURE_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "SELECTION_HISTORY_DEFINE_PROPERTY_CAPTURE_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-plan-history-define-capture-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "pack-collation-plan.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "pack-collation-plan.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${defineContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${defineMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.replace(/^not ok \d+ - /u, "") === defineContract).length, 1); assert.equal(lines.filter((line) => line.includes("SELECTION_HISTORY_DEFINE_PROPERTY_CAPTURE_MUST_SURVIVE_LIVE_SUBSTITUTION")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const freezeContract = "pack collation plan selection history captures freeze before live substitution";
const freezeMarker = "PACK_COLLATION_PLAN_SELECTION_HISTORY_FREEZE_CAPTURE_CONTRACT_EXECUTED";
test(freezeContract, async () => {
  console.log(freezeMarker);
  const moduleUrl = process.env[moduleKey] ?? sourcePath.href, directory = new URL("./", moduleUrl);
  const [pack, finite, transition, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("finite-batch-plan-position-transition.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]);
  const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]), safeDefine = Object.defineProperty, descriptor = Object.getOwnPropertyDescriptor(Object, "freeze"); let result;
  try { safeDefine(Object, "freeze", { ...descriptor, value: () => { throw new Error("poisoned live freeze"); } }); assert.doesNotThrow(() => { result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]); }, "SELECTION_HISTORY_FREEZE_CAPTURE_MUST_SURVIVE_LIVE_SUBSTITUTION"); } finally { safeDefine(Object, "freeze", descriptor); }
  const history = pack.readOmensPackCollationPlanSelectionHistoryForCompletion(result.nextPlan);
  assert.ok(Object.isFrozen(history), "SELECTION_HISTORY_FREEZE_CAPTURE_MUST_SURVIVE_LIVE_SUBSTITUTION"); assert.ok(Object.isFrozen(history[0]), "SELECTION_HISTORY_FREEZE_CAPTURE_MUST_SURVIVE_LIVE_SUBSTITUTION");
});
test("selection-history Object.freeze live-global mutation fails its exact named contract", () => {
  const anchor = "const freeze: typeof Object.freeze = Object.freeze;", replacement = "const freeze: typeof Object.freeze = ((value: object) => globalThis.Object.freeze(value)) as typeof Object.freeze;", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, replacement);
  assert.equal(original.split(anchor).length - 1, 1, "SELECTION_HISTORY_FREEZE_CAPTURE_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "SELECTION_HISTORY_FREEZE_CAPTURE_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-plan-history-freeze-capture-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "pack-collation-plan.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "pack-collation-plan.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${freezeContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${freezeMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.replace(/^not ok \d+ - /u, "") === freezeContract).length, 1); assert.equal(lines.filter((line) => line.includes("SELECTION_HISTORY_FREEZE_CAPTURE_MUST_SURVIVE_LIVE_SUBSTITUTION")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});
