import assert from "node:assert/strict";
import { Buffer } from "node:buffer";
import { spawnSync } from "node:child_process";
import { copyFileSync, mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import test from "node:test";
import { fictionalCollationCapabilities } from "./fictional-collation-capabilities.mjs";

const moduleKey = "DRAFT_TABLE_TEST_PACK_COLLATION_PLAN_SELECTION_HISTORY_MODULE";
const sourcePath = new URL("../src/pack-collation-plan.ts", import.meta.url);

const freshContract = "pack collation plan selection history starts exact empty";
const freshMarker = "PACK_COLLATION_PLAN_SELECTION_HISTORY_FRESH_CONTRACT_EXECUTED";
test(freshContract, async () => {
  console.log(freshMarker);
  const moduleUrl = process.env[moduleKey] ?? sourcePath.href, directory = new URL("./", moduleUrl);
  const [pack, finite, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]);
  const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }); let initialized;
  assert.doesNotThrow(() => { initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); const history = pack.readOmensPackCollationPlanSelectionHistoryForCompletion(initialized.plan); assert.equal(history.length, 0); assert.deepEqual(history, []); assert.ok(Object.isFrozen(history)); }, "FRESH_SELECTION_HISTORY_MUST_BE_EXACT_EMPTY");
});
test("fresh selection-history semantic mutation fails its exact named contract", () => {
  const anchor = "const freshSelectionHistory = (): OmensPackCollationPlanSelectionHistory => frozen([]);", original = readFileSync(sourcePath, "utf8");
  const mutated = original.replace(anchor, "const freshSelectionHistory = (): OmensPackCollationPlanSelectionHistory => frozen([undefined as unknown as OmensPackCollationPlanPositionSelection]);");
  assert.equal(original.split(anchor).length - 1, 1, "FRESH_HISTORY_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "FRESH_HISTORY_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-plan-history-fresh-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "pack-collation-plan.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "pack-collation-plan.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${freshContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${freshMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.replace(/^not ok \d+ - /u, "") === freshContract).length, 1); assert.equal(lines.filter((line) => line.includes("FRESH_SELECTION_HISTORY_MUST_BE_EXACT_EMPTY")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const appendContract = "pack collation plan selection history appends exact accepted current references";
const appendMarker = "PACK_COLLATION_PLAN_SELECTION_HISTORY_APPEND_CONTRACT_EXECUTED";
test(appendContract, async () => {
  console.log(appendMarker);
  const moduleUrl = process.env[moduleKey] ?? sourcePath.href, directory = new URL("./", moduleUrl);
  const [pack, finite, transition, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("finite-batch-plan-position-transition.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]);
  const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]); let first, second;
  assert.doesNotThrow(() => { first = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]); second = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(first.nextPlan, [0]); const history = pack.readOmensPackCollationPlanSelectionHistoryForCompletion(second.nextPlan), record = history[1]; assert.equal(record.positionReference, second.positionReference); assert.equal(record.officialIdentityReference, second.officialIdentityReference); assert.equal(record.positionReference, initialized.layoutReference.slots[1]); }, "APPENDED_RECORD_MUST_USE_EXACT_ACCEPTED_CURRENT_REFERENCES");
});
test("accepted-reference append semantic mutation fails its exact named contract", () => {
  const anchor = "    prior.selectionHistory, positionReference, officialIdentityReference\n  );", replacement = "    prior.selectionHistory, prior.layoutReference.slots[0], prior.tables.poolTables[0].officialIdentityChoices[0].officialIdentityReference\n  );", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, replacement);
  assert.equal(original.split(anchor).length - 1, 1, "APPEND_REFERENCE_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "APPEND_REFERENCE_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-plan-history-append-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "pack-collation-plan.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "pack-collation-plan.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${appendContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${appendMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.replace(/^not ok \d+ - /u, "") === appendContract).length, 1); assert.equal(lines.filter((line) => line.includes("APPENDED_RECORD_MUST_USE_EXACT_ACCEPTED_CURRENT_REFERENCES")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const orderContract = "pack collation plan selection history retains prior records in exact order and identity";
const orderMarker = "PACK_COLLATION_PLAN_SELECTION_HISTORY_ORDER_CONTRACT_EXECUTED";
test(orderContract, async () => {
  console.log(orderMarker);
  const moduleUrl = process.env[moduleKey] ?? sourcePath.href, directory = new URL("./", moduleUrl);
  const [pack, finite, transition, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("finite-batch-plan-position-transition.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]);
  const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]);
  assert.doesNotThrow(() => { const first = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]), second = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(first.nextPlan, [0]), prior = pack.readOmensPackCollationPlanSelectionHistoryForCompletion(second.nextPlan), third = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(second.nextPlan, [0]), next = pack.readOmensPackCollationPlanSelectionHistoryForCompletion(third.nextPlan); assert.equal(next[0], prior[0]); assert.equal(next[1], prior[1]); }, "PRIOR_HISTORY_RECORDS_MUST_RETAIN_EXACT_ORDER_AND_IDENTITY");
});
test("prior-record order semantic mutation fails its exact named contract", () => {
  const anchor = "    defineOwnDataProperty(history, index, { value: priorRecord, writable: false, enumerable: true, configurable: false });", replacement = "    defineOwnDataProperty(history, index, { value: prior[prior.length - 1 - index], writable: false, enumerable: true, configurable: false });", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, replacement);
  assert.equal(original.split(anchor).length - 1, 1, "PRIOR_ORDER_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "PRIOR_ORDER_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-plan-history-order-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "pack-collation-plan.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "pack-collation-plan.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${orderContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${orderMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.replace(/^not ok \d+ - /u, "") === orderContract).length, 1); assert.equal(lines.filter((line) => line.includes("PRIOR_HISTORY_RECORDS_MUST_RETAIN_EXACT_ORDER_AND_IDENTITY")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const cursorContract = "pack collation plan selection history length equals every registered cursor";
const cursorMarker = "PACK_COLLATION_PLAN_SELECTION_HISTORY_CURSOR_CONTRACT_EXECUTED";
test(cursorContract, async () => {
  console.log(cursorMarker);
  const moduleUrl = process.env[moduleKey] ?? sourcePath.href, directory = new URL("./", moduleUrl);
  const [pack, finite, transition, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("finite-batch-plan-position-transition.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]);
  const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]);
  assert.doesNotThrow(() => { const result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]); assert.equal(pack.readOmensPackCollationPlanSelectionHistoryForCompletion(result.nextPlan).length, pack.readOmensPackCollationPlanNextPositionForTransition(result.nextPlan)); }, "REGISTERED_CURSOR_MUST_EQUAL_SELECTION_HISTORY_LENGTH");
});
test("cursor-history equality semantic mutation fails its exact named contract", () => {
  const anchor = "    nextPosition: prior.nextPosition + 1,\n    selectionHistory", replacement = "    nextPosition: prior.nextPosition + 2,\n    selectionHistory", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, replacement);
  assert.equal(original.split(anchor).length - 1, 1, "CURSOR_HISTORY_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "CURSOR_HISTORY_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-plan-history-cursor-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "pack-collation-plan.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "pack-collation-plan.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${cursorContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${cursorMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.replace(/^not ok \d+ - /u, "") === cursorContract).length, 1); assert.equal(lines.filter((line) => line.includes("REGISTERED_CURSOR_MUST_EQUAL_SELECTION_HISTORY_LENGTH")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const oldContract = "pack collation plan selection history never reuses or mutates the old history";
const oldMarker = "PACK_COLLATION_PLAN_SELECTION_HISTORY_OLD_VALUE_CONTRACT_EXECUTED";
test(oldContract, async () => {
  console.log(oldMarker);
  const moduleUrl = process.env[moduleKey] ?? sourcePath.href, directory = new URL("./", moduleUrl);
  const [pack, finite, transition, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("finite-batch-plan-position-transition.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]);
  const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]), oldHistory = pack.readOmensPackCollationPlanSelectionHistoryForCompletion(initialized.plan);
  assert.doesNotThrow(() => { const result = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]), nextHistory = pack.readOmensPackCollationPlanSelectionHistoryForCompletion(result.nextPlan); assert.notEqual(nextHistory, oldHistory); assert.equal(oldHistory.length, 0); assert.ok(Object.isFrozen(oldHistory)); }, "OLD_SELECTION_HISTORY_MUST_NOT_BE_REUSED_OR_MUTATED");
});
test("old-history reuse semantic mutation fails its exact named contract", () => {
  const anchor = "  const history: OmensPackCollationPlanPositionSelection[] = [];", replacement = "  const history = prior as OmensPackCollationPlanPositionSelection[];", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, replacement);
  assert.equal(original.split(anchor).length - 1, 1, "OLD_HISTORY_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "OLD_HISTORY_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-plan-history-old-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "pack-collation-plan.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "pack-collation-plan.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${oldContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${oldMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.replace(/^not ok \d+ - /u, "") === oldContract).length, 1); assert.equal(lines.filter((line) => line.includes("OLD_SELECTION_HISTORY_MUST_NOT_BE_REUSED_OR_MUTATED")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});

const siblingContract = "pack collation plan sibling transitions never share minted selection records or histories";
const siblingMarker = "PACK_COLLATION_PLAN_SELECTION_HISTORY_SIBLING_FRESHNESS_CONTRACT_EXECUTED";
test(siblingContract, async () => {
  console.log(siblingMarker);
  const moduleUrl = process.env[moduleKey] ?? sourcePath.href, directory = new URL("./", moduleUrl);
  const [pack, finite, transition, custom, eligibility, layouts, upstream, pools, identity, layoutResolution, poolResolution, compiler] = await Promise.all([import(moduleUrl), import(new URL("finite-batch-collation-plan.ts", directory)), import(new URL("finite-batch-plan-position-transition.ts", directory)), import(new URL("custom-cards.ts", directory)), import(new URL("draft-eligibility-classification.ts", directory)), import(new URL("layouts.ts", directory)), import(new URL("official-upstream-id-reconciliation.ts", directory)), import(new URL("pools.ts", directory)), import(new URL("recipe-official-identity-reconciliation.ts", directory)), import(new URL("recipe-layout-pool-resolution.ts", directory)), import(new URL("recipe-pool-identity-resolution.ts", directory)), import(new URL("collation-weight-tables.ts", directory))]);
  const { tables } = fictionalCollationCapabilities({ ...custom, ...eligibility, ...layouts, ...upstream, ...pools, ...identity, ...layoutResolution, ...poolResolution, ...compiler }), initialized = finite.initializeOmensPackCollationPlanFromUnsigned32SampleBatch(tables, [0]);
  assert.doesNotThrow(() => { const first = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]), second = transition.transitionOmensPackCollationPlanCurrentPositionFromUnsigned32SampleBatch(initialized.plan, [0]), firstHistory = pack.readOmensPackCollationPlanSelectionHistoryForCompletion(first.nextPlan), secondHistory = pack.readOmensPackCollationPlanSelectionHistoryForCompletion(second.nextPlan); assert.notEqual(firstHistory, secondHistory); assert.notEqual(firstHistory[0], secondHistory[0]); }, "SIBLING_TRANSITIONS_MUST_NOT_SHARE_MINTED_HISTORY_OR_RECORD");
});
test("sibling history-record freshness semantic mutation fails its exact named contract", () => {
  const anchor = "  return frozen(history);", replacement = "  return ((globalThis as typeof globalThis & { __draftTableSiblingHistory?: OmensPackCollationPlanSelectionHistory }).__draftTableSiblingHistory ??= frozen(history));", original = readFileSync(sourcePath, "utf8"), mutated = original.replace(anchor, replacement);
  assert.equal(original.split(anchor).length - 1, 1, "SIBLING_FRESHNESS_ANCHOR_MUST_BE_UNIQUE"); assert.notEqual(Buffer.compare(Buffer.from(original), Buffer.from(mutated)), 0, "SIBLING_FRESHNESS_MUTATION_BYTES_MUST_CHANGE");
  let snapshot; try { snapshot = mkdtempSync(join(tmpdir(), "draft-table-plan-history-sibling-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((entry) => entry.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(snapshot, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(snapshot, "node_modules"), "dir"); writeFileSync(join(snapshot, "pack-collation-plan.ts"), mutated); writeFileSync(join(snapshot, "tsconfig.json"), '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","strict":true,"noEmit":true,"allowImportingTsExtensions":true},"include":["*.ts"]}'); const checked = spawnSync(join(snapshot, "node_modules", ".bin", "tsc"), ["-p", join(snapshot, "tsconfig.json")], { encoding: "utf8" }); assert.equal(checked.status, 0, `${checked.stdout}\n${checked.stderr}`); const environment = { ...process.env, [moduleKey]: pathToFileURL(join(snapshot, "pack-collation-plan.ts")).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", `^${siblingContract.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${siblingMarker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.replace(/^not ok \d+ - /u, "") === siblingContract).length, 1); assert.equal(lines.filter((line) => line.includes("SIBLING_TRANSITIONS_MUST_NOT_SHARE_MINTED_HISTORY_OR_RECORD")).length, 1); } finally { if (snapshot !== undefined) rmSync(snapshot, { recursive: true, force: true }); }
});
