import assert from "node:assert/strict";
import { Buffer } from "node:buffer";
import { spawnSync } from "node:child_process";
import { copyFileSync, existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve as resolvePath, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import test from "node:test";
import { UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END } from "@draft-table/engine";
import { exactTestNamePattern } from "./recipe-layout-pool-resolution-test-name.mjs";
import { completeOmensRecipeCustomCardsAggregateForTest, parseOmensCustomCardsFromTrustedBytes } from "../src/custom-cards.ts";
import { classifyOmensDraftEligibilityForTest } from "../src/draft-eligibility-classification.ts";
import { parseOmensLayoutsFromTrustedBytes } from "../src/layouts.ts";
import { reconcileOfficialUpstreamIdRecordsForTest } from "../src/official-upstream-id-reconciliation.ts";
import { completeOmensRecipePoolsForTest, parseOmensPoolsFromTrustedBytes } from "../src/pools.ts";
import { reconcileOmensRecipeOfficialIdentityRecordsForTest } from "../src/recipe-official-identity-reconciliation.ts";
import { resolveOmensRecipeLayoutsToOfficialIdentityPoolsForTest } from "../src/recipe-layout-pool-resolution.ts";
import { resolveOmensRecipePoolsToDraftableOfficialIdentitiesForTest } from "../src/recipe-pool-identity-resolution.ts";
import { compileOmensCollationWeightTablesForTest } from "../src/collation-weight-tables.ts";
import { initializeOmensPackLocalPoolDrawState } from "../src/pack-local-pool-draw-state.ts";
import {
  OmensPackLocalPoolSampleDrawTransitionError,
  drawOmensPackLocalPoolOfficialIdentityFromOneUnsigned32Sample
} from "../src/pack-local-pool-sample-draw-transition.ts";

const settings = JSON.stringify({ showSlots: true, withReplacement: false, cardBack: "https://cards.invalid/back.png" });
const cards = Object.freeze([["Fictional A", "OMN100", "common"], ["Fictional B", "OMN101", "common"], ["Fictional C", "OMN102", "common"], ["Fictional I", "OMN103", "common"], ["Fictional R", "OMN104", "common"], ["Fictional L", "OMN105", "common"], ["Fictional G", "OMN106", "common"], ["Fictional E", "OMN107", "common"], ["Fictional Rare", "OMN108", "rare"], ["Fictional Majestic", "OMN109", "mythic"]]);
const pools = Object.freeze([["Wizard", [[2, "Fictional A"], [3, "Fictional B"], [3, "Fictional C"]]], ["Illusionist", [[7, "Fictional I"]]], ["Runeblade", [[4, "Fictional R"]]], ["Lightning", [[6, "Fictional L"]]], ["Generic", [[8, "Fictional G"]]], ["Equipment", [[9, "Fictional E"]]], ["Rare", [[10, "Fictional Rare"]]], ["Majestic", [[11, "Fictional Majestic"]]], ["Rfcommon", [[12, "Fictional A"]]], ["RFRare", [[13, "Fictional Rare"]]], ["RFMajestic", [[14, "Fictional Majestic"]]]]);
const card = ([name, collector_number, rarity]) => ({ name, collector_number, mana_cost: "2", rarity, type: "action", image_uris: { en: "https://cards.invalid/a.png" } });
const layout = (index) => `\t- Fictional Layout ${index + 1} (${index === 227 ? 6800 : 2000})\r\n\t\t3 Wizard\r\n\t\t2 Illusionist\r\n\t\t2 Runeblade\r\n\t\t1 Lightning\r\n\t\t1 Generic\r\n\t\t2 Equipment\r\n\t\t1 Rare\r\n\t\t1 ${index < 114 ? "Rare" : "Majestic"}\r\n\t\t1 ${["Rfcommon", "RFRare", "RFMajestic"][index % 3]}`;
const recipeBytes = () => Buffer.from(`\ufeff[Settings]\r\n${settings}\r\n[CustomCards]\r\n${JSON.stringify(cards.map(card))}\r\n[Layouts]\r\n${Array.from({ length: 228 }, (_, index) => layout(index)).join("\r\n")}\r\n${pools.map(([label, entries]) => `[${label}]\r\n${entries.map(([weight, reference]) => `${weight} ${reference}`).join("\r\n")}`).join("\r\n")}`, "utf8");
const forms = Object.freeze([...cards.map(([, id]) => Object.freeze({ officialPrintId: id, baseCollectorId: id, sourceSet: "OMN", suffixMarker: null })), Object.freeze({ officialPrintId: "IAR200-MV", baseCollectorId: "IAR200", sourceSet: "IAR", suffixMarker: "MV" })]);

const capabilities = (modules = { custom: { completeOmensRecipeCustomCardsAggregateForTest, parseOmensCustomCardsFromTrustedBytes }, eligibility: { classifyOmensDraftEligibilityForTest }, layouts: { parseOmensLayoutsFromTrustedBytes }, upstream: { reconcileOfficialUpstreamIdRecordsForTest }, pools: { completeOmensRecipePoolsForTest, parseOmensPoolsFromTrustedBytes }, identity: { reconcileOmensRecipeOfficialIdentityRecordsForTest }, poolResolution: { resolveOmensRecipePoolsToDraftableOfficialIdentitiesForTest }, layoutResolution: { resolveOmensRecipeLayoutsToOfficialIdentityPoolsForTest }, compiler: { compileOmensCollationWeightTablesForTest } }) => {
  const bytes = recipeBytes(), references = modules.custom.completeOmensRecipeCustomCardsAggregateForTest(modules.custom.parseOmensCustomCardsFromTrustedBytes(bytes), { common: 8, rare: 1, mythic: 1 }), layouts = modules.layouts.parseOmensLayoutsFromTrustedBytes(bytes), completed = modules.pools.completeOmensRecipePoolsForTest(modules.pools.parseOmensPoolsFromTrustedBytes(bytes), layouts, references);
  const names = new Map([...cards.map(([name, id]) => [id, name]), ["IAR200", "Excluded"]]), source = forms.map((form, index) => ({ unique_id: `fictional-card-${index}`, name: names.get(form.baseCollectorId), pitch: "", printings: [{ unique_id: `fictional-printing-${index}`, set_printing_unique_id: `fictional-set-${form.sourceSet}`, id: form.baseCollectorId, set_id: form.sourceSet, edition: "standard", foiling: "standard", rarity: "C", expansion_slot: false, image_url: "https://cards.invalid/a.png", art_variations: [] }] }));
  const official = modules.upstream.reconcileOfficialUpstreamIdRecordsForTest(forms, source, { entries: 11, omnEntries: 10, iarEntries: 1, omnPrintings: 10, iarPrintings: 1 }), identities = modules.identity.reconcileOmensRecipeOfficialIdentityRecordsForTest(references, official, { recipeEntries: 10, officialEntries: 11, candidateEntries: 10, mappedEntries: 10, unmappedEntries: 1, unmappedOmn: 0, unmappedIar: 1, unmappedUnsuffixed: 0, unmappedRf: 0, unmappedCf: 0, unmappedMv: 1 }), eligibility = modules.eligibility.classifyOmensDraftEligibilityForTest(identities, official, { officialEntries: 11, mappedEntries: 10, mappedIarEntries: 0, excludedEntries: 1, excludedIarEntries: 1, excludedNonIarEntries: 0, unclassifiedEntries: 0, unclassifiedOmnEntries: 0, unclassifiedIarEntries: 0, unclassifiedUnsuffixed: 0, unclassifiedRf: 0, unclassifiedCf: 0, unclassifiedMv: 0 });
  const resolved = modules.poolResolution.resolveOmensRecipePoolsToDraftableOfficialIdentitiesForTest(completed, identities, eligibility);
  return { tables: modules.compiler.compileOmensCollationWeightTablesForTest(modules.layoutResolution.resolveOmensRecipeLayoutsToOfficialIdentityPoolsForTest(layouts, resolved), resolved) };
};

const cutoff = (bound) => UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END - UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END % bound;
const safe = (action) => assert.throws(action, (error) => { assert.ok(error instanceof OmensPackLocalPoolSampleDrawTransitionError); assert.equal(error.code, "OMENS_PACK_LOCAL_POOL_SAMPLE_DRAW_TRANSITION_FAILED"); assert.equal(error.message, "Omens one-sample pack local pool draw transition failed."); assert.equal(error.stack, "OmensPackLocalPoolSampleDrawTransitionError: Omens one-sample pack local pool draw transition failed."); assert.deepEqual(JSON.parse(JSON.stringify(error)), { name: "OmensPackLocalPoolSampleDrawTransitionError", code: "OMENS_PACK_LOCAL_POOL_SAMPLE_DRAW_TRANSITION_FAILED" }); assert.doesNotMatch(`${error.message}${error.stack}${JSON.stringify(error)}`, /Fictional|OMN|IAR|[0-9]|https?:|\\|\//iu); return true; });
const assertRetry = (result) => { assert.deepEqual(result, { state: "retry" }); assert.ok(Object.isFrozen(result)); assert.deepEqual(Object.keys(result), ["state"]); };
const expectedAfterRemoval = (state, poolIndex, selected) => {
  const source = state.poolStates[poolIndex], choices = source.officialIdentityChoices.filter((choice) => choice.officialIdentityReference !== selected); let end = 0;
  return { total: source.poolTotalWeight - source.officialIdentityChoices.find((choice) => choice.officialIdentityReference === selected).weight, choices: choices.map((choice) => ({ identity: choice.officialIdentityReference, weight: choice.weight, end: (end += choice.weight) })) };
};
const assertExactTransition = (state, poolIndex, sample, draw = drawOmensPackLocalPoolOfficialIdentityFromOneUnsigned32Sample) => {
  const pool = state.poolStates[poolIndex], ticket = sample % pool.poolTotalWeight, expectedChoice = pool.officialIdentityChoices.find((choice) => choice.cumulativeExclusiveEnd > ticket), expected = expectedAfterRemoval(state, poolIndex, expectedChoice.officialIdentityReference), before = structuredClone(state), result = draw(state, pool.poolReference, sample);
  assert.equal(result.state, "selected"); assert.equal(result.officialIdentityReference, expectedChoice.officialIdentityReference); assert.notEqual(result.nextState, state); assert.ok(Object.isFrozen(result)); assert.ok(Object.isFrozen(result.nextState)); assert.deepEqual(Object.keys(result).sort(), ["nextState", "officialIdentityReference", "state"]);
  const output = result.nextState.poolStates[poolIndex]; assert.equal(output.poolTotalWeight, expected.total); assert.deepEqual(output.officialIdentityChoices.map((choice) => ({ identity: choice.officialIdentityReference, weight: choice.weight, end: choice.cumulativeExclusiveEnd })), expected.choices); for (let index = 0; index < state.poolStates.length; index++) if (index !== poolIndex) assert.equal(result.nextState.poolStates[index], state.poolStates[index]); assert.deepEqual(state, before); return result;
};

test("one pack-local sample atomically retries or selects and removes first middle last choices", () => {
  const { tables } = capabilities(), state = initializeOmensPackLocalPoolDrawState(tables), pool = state.poolStates[0];
  for (const sample of [0, pool.officialIdentityChoices[0].cumulativeExclusiveEnd, pool.poolTotalWeight - 1]) assertExactTransition(state, 0, sample);
  const retryPool = state.poolStates[1], before = structuredClone(state); assertRetry(drawOmensPackLocalPoolOfficialIdentityFromOneUnsigned32Sample(state, retryPool.poolReference, cutoff(retryPool.poolTotalWeight))); assert.deepEqual(state, before);
});

test("atomic pack-local transition is deterministic, sequential, exact-pool scoped, and exhausts one-entry pools", () => {
  const { tables } = capabilities(), initial = initializeOmensPackLocalPoolDrawState(tables), normal = initial.poolStates[0], rainbow = initial.poolStates[8], first = assertExactTransition(initial, 0, 0), second = assertExactTransition(first.nextState, 0, 0), third = assertExactTransition(second.nextState, 0, 0);
  assert.notEqual(first.officialIdentityReference, second.officialIdentityReference); assert.notEqual(second.officialIdentityReference, third.officialIdentityReference); assert.equal(third.nextState.poolStates[0].poolTotalWeight, 0); assert.deepEqual(third.nextState.poolStates[0].officialIdentityChoices, []); safe(() => drawOmensPackLocalPoolOfficialIdentityFromOneUnsigned32Sample(third.nextState, normal.poolReference, 0));
  assert.deepEqual(normal.officialIdentityChoices[0].officialIdentityReference, rainbow.officialIdentityChoices[0].officialIdentityReference); assert.equal(first.nextState.poolStates[8], rainbow); assert.equal(first.nextState.poolStates[8].officialIdentityChoices[0].officialIdentityReference, rainbow.officialIdentityChoices[0].officialIdentityReference);
  const again = assertExactTransition(initial, 0, 0); assert.equal(again.officialIdentityReference, first.officialIdentityReference); assert.deepEqual(again.nextState, first.nextState); assert.notEqual(again.nextState, first.nextState);
  const one = assertExactTransition(initial, 1, 0); assert.equal(one.nextState.poolStates[1].poolTotalWeight, 0); assert.deepEqual(one.nextState.poolStates[1].officialIdentityChoices, []);
});

test("small-table property maps every accepted ticket to its selected identity and independent exact next-state oracle", () => {
  const { tables } = capabilities(), state = initializeOmensPackLocalPoolDrawState(tables);
  for (let poolIndex = 0; poolIndex < state.poolStates.length; poolIndex++) {
    const pool = state.poolStates[poolIndex], before = structuredClone(state);
    for (let ticket = 0; ticket < pool.poolTotalWeight; ticket++) assertExactTransition(state, poolIndex, ticket);
    const accepted = cutoff(pool.poolTotalWeight); if (accepted < UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END) assertRetry(drawOmensPackLocalPoolOfficialIdentityFromOneUnsigned32Sample(state, pool.poolReference, accepted)); assert.deepEqual(state, before);
  }
});

test("atomic transition rejects invalid exhausted copied foreign and mixed capabilities without effects", () => {
  const first = capabilities(), second = capabilities(), state = initializeOmensPackLocalPoolDrawState(first.tables), foreign = initializeOmensPackLocalPoolDrawState(second.tables), pool = state.poolStates[0], before = structuredClone(state), exhausted = assertExactTransition(state, 1, 0).nextState;
  safe(() => drawOmensPackLocalPoolOfficialIdentityFromOneUnsigned32Sample(exhausted, exhausted.poolStates[1].poolReference, 0));
  for (const sample of [-1, 0.5, NaN, Infinity, UINT32_SAMPLE_DOMAIN_EXCLUSIVE_END, "0", null, undefined]) safe(() => drawOmensPackLocalPoolOfficialIdentityFromOneUnsigned32Sample(state, pool.poolReference, sample));
  safe(() => drawOmensPackLocalPoolOfficialIdentityFromOneUnsigned32Sample()); safe(() => drawOmensPackLocalPoolOfficialIdentityFromOneUnsigned32Sample(state, pool.poolReference, 0, "override")); safe(() => drawOmensPackLocalPoolOfficialIdentityFromOneUnsigned32Sample(structuredClone(state), pool.poolReference, 0)); safe(() => drawOmensPackLocalPoolOfficialIdentityFromOneUnsigned32Sample(state, structuredClone(pool.poolReference), 0)); safe(() => drawOmensPackLocalPoolOfficialIdentityFromOneUnsigned32Sample(state, foreign.poolStates[0].poolReference, 0)); safe(() => drawOmensPackLocalPoolOfficialIdentityFromOneUnsigned32Sample(Object.freeze({ poolStates: Object.freeze([]) }), pool.poolReference, 0)); assert.deepEqual(state, before);
});

test("atomic pack-local draw composition owns no entropy retry loop layout sequencing or runtime policy", () => {
  const source = readFileSync(new URL("../src/pack-local-pool-sample-draw-transition.ts", import.meta.url), "utf8");
  assert.doesNotMatch(source, /Math\.random|crypto|randomBytes|randomUUID|while\s*\(|for\s*\(|%|layout|slot|pack construction|card instance|rear|treatment|printing|image|snapshot|room|simulation|console\.|process\./iu);
});

const mutationModuleKey = "DRAFT_TABLE_TEST_PACK_LOCAL_POOL_SAMPLE_DRAW_TRANSITION_MODULE";
const sourcePath = new URL("../src/pack-local-pool-sample-draw-transition.ts", import.meta.url);
const withCanonicalSnapshot = (action) => { let directory; try { directory = mkdtempSync(join(tmpdir(), "draft-table-pack-local-pool-sample-draw-transition-mutation-")); const sourceDirectory = fileURLToPath(new URL("../src/", import.meta.url)); for (const file of readdirSync(sourceDirectory).filter((file) => file.endsWith(".ts"))) copyFileSync(join(sourceDirectory, file), join(directory, file)); symlinkSync(join(sourceDirectory, "../../../node_modules"), join(directory, "node_modules"), "dir"); return action(directory); } finally { if (directory !== undefined) rmSync(directory, { recursive: true, force: true }); } };
const loadMutationModules = async () => { const moduleUrl = process.env[mutationModuleKey] ?? sourcePath.href, directory = new URL("./", moduleUrl); return { transition: await import(moduleUrl), state: await import(new URL("pack-local-pool-draw-state.ts", directory)), compiler: await import(new URL("collation-weight-tables.ts", directory)), custom: await import(new URL("custom-cards.ts", directory)), eligibility: await import(new URL("draft-eligibility-classification.ts", directory)), layouts: await import(new URL("layouts.ts", directory)), upstream: await import(new URL("official-upstream-id-reconciliation.ts", directory)), pools: await import(new URL("pools.ts", directory)), identity: await import(new URL("recipe-official-identity-reconciliation.ts", directory)), poolResolution: await import(new URL("recipe-pool-identity-resolution.ts", directory)), layoutResolution: await import(new URL("recipe-layout-pool-resolution.ts", directory)) }; };
const runMutation = (mutated, contractName, marker, failure) => withCanonicalSnapshot((directory) => { const path = join(directory, "pack-local-pool-sample-draw-transition.ts"); writeFileSync(path, mutated); const environment = { ...process.env, [mutationModuleKey]: pathToFileURL(path).href }; delete environment.NODE_TEST_CONTEXT; const result = spawnSync(process.execPath, ["--experimental-strip-types", "--test", "--test-name-pattern", exactTestNamePattern(contractName), fileURLToPath(import.meta.url)], { encoding: "utf8", env: environment }), lines = result.stdout.split(/\r?\n/u); assert.equal(result.status, 1, `${result.stdout}\n${result.stderr}`); assert.equal(lines.filter((line) => line === `# ${marker}`).length, 1); assert.equal(lines.filter((line) => /^not ok \d+ - /u.test(line) && line.replace(/^not ok \d+ - /u, "") === contractName).length, 1); assert.equal(lines.filter((line) => line.includes(failure)).length, 1); });

const retryContract = "pack-local atomic draw retry cannot invoke same-pool removal", retryMarker = "PACK_LOCAL_ATOMIC_DRAW_RETRY_CONTRACT_EXECUTED";
test(retryContract, async () => { console.log(retryMarker); const m = await loadMutationModules(), { tables } = capabilities(m), state = m.state.initializeOmensPackLocalPoolDrawState(tables), pool = state.poolStates[1], result = m.transition.drawOmensPackLocalPoolOfficialIdentityFromOneUnsigned32Sample(state, pool.poolReference, cutoff(pool.poolTotalWeight)); assert.equal(result.state, "retry", "RETRY_MUST_NOT_INVOKE_OR_RETURN_REMOVAL"); });
test("atomic-draw retry-removal semantic mutation fails its exact named contract", () => { const original = readFileSync(sourcePath, "utf8"); const mutated = original.replace("if (selection.state === \"retry\") return retry();", "if (selection.state === \"retry\") return selected(state.poolStates[1].officialIdentityChoices[0].officialIdentityReference, removeOmensPackLocalPoolOfficialIdentity(state, poolReference, state.poolStates[1].officialIdentityChoices[0].officialIdentityReference));"); assert.notEqual(mutated, original); runMutation(mutated, retryContract, retryMarker, "RETRY_MUST_NOT_INVOKE_OR_RETURN_REMOVAL"); });

const nextStateContract = "pack-local atomic draw selected result owns a distinct removed next state", nextStateMarker = "PACK_LOCAL_ATOMIC_DRAW_NEXT_STATE_CONTRACT_EXECUTED";
test(nextStateContract, async () => { console.log(nextStateMarker); const m = await loadMutationModules(), { tables } = capabilities(m), state = m.state.initializeOmensPackLocalPoolDrawState(tables), pool = state.poolStates[0], result = m.transition.drawOmensPackLocalPoolOfficialIdentityFromOneUnsigned32Sample(state, pool.poolReference, 0); assert.notEqual(result.nextState, state, "SELECTED_RESULT_MUST_NOT_RETURN_ORIGINAL_STATE"); assert.equal(result.nextState.poolStates[0].officialIdentityChoices.length, state.poolStates[0].officialIdentityChoices.length - 1, "SELECTED_RESULT_MUST_NOT_SKIP_REMOVAL"); });
test("atomic-draw original-state semantic mutation fails its exact named contract", () => { const original = readFileSync(sourcePath, "utf8"); const mutated = original.replace("const nextState = removeOmensPackLocalPoolOfficialIdentity(state, poolReference, selection.officialIdentityReference);", "const nextState = state;").replace("if (nextState === state) return fail();", "if (false) return fail();"); assert.notEqual(mutated, original); runMutation(mutated, nextStateContract, nextStateMarker, "SELECTED_RESULT_MUST_NOT_RETURN_ORIGINAL_STATE"); });

const identityContract = "pack-local atomic draw removes the exact selected identity", identityMarker = "PACK_LOCAL_ATOMIC_DRAW_IDENTITY_CONTRACT_EXECUTED";
test(identityContract, async () => { console.log(identityMarker); const m = await loadMutationModules(), { tables } = capabilities(m), state = m.state.initializeOmensPackLocalPoolDrawState(tables), pool = state.poolStates[0], result = m.transition.drawOmensPackLocalPoolOfficialIdentityFromOneUnsigned32Sample(state, pool.poolReference, 2); assert.equal(result.nextState.poolStates[0].officialIdentityChoices.some((choice) => choice.officialIdentityReference === result.officialIdentityReference), false, "EXACT_SELECTED_IDENTITY_MUST_DISAPPEAR"); });
test("atomic-draw selected-identity semantic mutation fails its exact named contract", () => { const original = readFileSync(sourcePath, "utf8"); const mutated = original.replace("poolReference, selection.officialIdentityReference", "poolReference, state.poolStates[0].officialIdentityChoices[0].officialIdentityReference"); assert.notEqual(mutated, original); runMutation(mutated, identityContract, identityMarker, "EXACT_SELECTED_IDENTITY_MUST_DISAPPEAR"); });

const scopeContract = "pack-local atomic draw removes only from the exact selected pool scope", scopeMarker = "PACK_LOCAL_ATOMIC_DRAW_SCOPE_CONTRACT_EXECUTED";
test(scopeContract, async () => { console.log(scopeMarker); const m = await loadMutationModules(), { tables } = capabilities(m), state = m.state.initializeOmensPackLocalPoolDrawState(tables), pool = state.poolStates[0], rainbow = state.poolStates[8], result = m.transition.drawOmensPackLocalPoolOfficialIdentityFromOneUnsigned32Sample(state, pool.poolReference, 0); assert.notEqual(result.nextState.poolStates[0], pool, "EXACT_SELECTED_POOL_MUST_CHANGE"); assert.equal(result.nextState.poolStates[8], rainbow, "SAME_IDENTITY_OTHER_POOL_MUST_REMAIN"); });
test("atomic-draw exact-pool scope semantic mutation fails its exact named contract", () => { const original = readFileSync(sourcePath, "utf8"); const mutated = original.replace("poolReference, selection.officialIdentityReference", "state.poolStates[8].poolReference, state.poolStates[8].officialIdentityChoices[0].officialIdentityReference"); assert.notEqual(mutated, original); runMutation(mutated, scopeContract, scopeMarker, "EXACT_SELECTED_POOL_MUST_CHANGE"); });

test("atomic draw mutation snapshots are file-local OS-temp canonical copies and always clean", () => { let snapshot; withCanonicalSnapshot((directory) => { snapshot = directory; assert.ok(directory.startsWith(tmpdir())); assert.equal(directory.startsWith(`${resolvePath(fileURLToPath(new URL("../../..", import.meta.url)))}${sep}`), false); }); assert.equal(existsSync(snapshot), false); let failed; assert.throws(() => withCanonicalSnapshot((directory) => { failed = directory; throw new Error("body"); })); assert.equal(existsSync(failed), false); });
